// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class PullNotifyResults;
@class PullNotifyResults_Builder;
@class PullNotifyResults_NotifyMsgSArgs;
@class PullNotifyResults_NotifyMsgSArgs_Builder;

@interface PullNotifyResultsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface PullNotifyResults : PBGeneratedMessage {
@private
  BOOL hasIsCompleted_:1;
  BOOL hasSyncId_:1;
  BOOL hasStatusCode_:1;
  BOOL isCompleted_:1;
  int64_t syncId;
  int32_t statusCode;
  NSMutableArray* mutableArgsListList;
}
- (BOOL) hasStatusCode;
- (BOOL) hasIsCompleted;
- (BOOL) hasSyncId;
@property (readonly) int32_t statusCode;
- (BOOL) isCompleted;
@property (readonly) int64_t syncId;
- (NSArray*) argsListList;
- (PullNotifyResults_NotifyMsgSArgs*) argsListAtIndex:(int32_t) index;

+ (PullNotifyResults*) defaultInstance;
- (PullNotifyResults*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PullNotifyResults_Builder*) builder;
+ (PullNotifyResults_Builder*) builder;
+ (PullNotifyResults_Builder*) builderWithPrototype:(PullNotifyResults*) prototype;

+ (PullNotifyResults*) parseFromData:(NSData*) data;
+ (PullNotifyResults*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PullNotifyResults*) parseFromInputStream:(NSInputStream*) input;
+ (PullNotifyResults*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PullNotifyResults*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PullNotifyResults*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PullNotifyResults_NotifyMsgSArgs : PBGeneratedMessage {
@private
  BOOL hasSourceId_:1;
  BOOL hasTid_:1;
  BOOL hasNotifyType_:1;
  BOOL hasNotifyId_:1;
  BOOL hasNotifyBody_:1;
  NSString* sourceId;
  NSString* tid;
  NSString* notifyType;
  NSString* notifyId;
  NSData* notifyBody;
}
- (BOOL) hasSourceId;
- (BOOL) hasTid;
- (BOOL) hasNotifyType;
- (BOOL) hasNotifyId;
- (BOOL) hasNotifyBody;
@property (readonly, retain) NSString* sourceId;
@property (readonly, retain) NSString* tid;
@property (readonly, retain) NSString* notifyType;
@property (readonly, retain) NSString* notifyId;
@property (readonly, retain) NSData* notifyBody;

+ (PullNotifyResults_NotifyMsgSArgs*) defaultInstance;
- (PullNotifyResults_NotifyMsgSArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) builder;
+ (PullNotifyResults_NotifyMsgSArgs_Builder*) builder;
+ (PullNotifyResults_NotifyMsgSArgs_Builder*) builderWithPrototype:(PullNotifyResults_NotifyMsgSArgs*) prototype;

+ (PullNotifyResults_NotifyMsgSArgs*) parseFromData:(NSData*) data;
+ (PullNotifyResults_NotifyMsgSArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PullNotifyResults_NotifyMsgSArgs*) parseFromInputStream:(NSInputStream*) input;
+ (PullNotifyResults_NotifyMsgSArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PullNotifyResults_NotifyMsgSArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PullNotifyResults_NotifyMsgSArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PullNotifyResults_NotifyMsgSArgs_Builder : PBGeneratedMessage_Builder {
@private
  PullNotifyResults_NotifyMsgSArgs* result;
}

- (PullNotifyResults_NotifyMsgSArgs*) defaultInstance;

- (PullNotifyResults_NotifyMsgSArgs_Builder*) clear;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) clone;

- (PullNotifyResults_NotifyMsgSArgs*) build;
- (PullNotifyResults_NotifyMsgSArgs*) buildPartial;

- (PullNotifyResults_NotifyMsgSArgs_Builder*) mergeFrom:(PullNotifyResults_NotifyMsgSArgs*) other;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSourceId;
- (NSString*) sourceId;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) setSourceId:(NSString*) value;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) clearSourceId;

- (BOOL) hasTid;
- (NSString*) tid;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) setTid:(NSString*) value;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) clearTid;

- (BOOL) hasNotifyType;
- (NSString*) notifyType;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) setNotifyType:(NSString*) value;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) clearNotifyType;

- (BOOL) hasNotifyId;
- (NSString*) notifyId;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) setNotifyId:(NSString*) value;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) clearNotifyId;

- (BOOL) hasNotifyBody;
- (NSData*) notifyBody;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) setNotifyBody:(NSData*) value;
- (PullNotifyResults_NotifyMsgSArgs_Builder*) clearNotifyBody;
@end

@interface PullNotifyResults_Builder : PBGeneratedMessage_Builder {
@private
  PullNotifyResults* result;
}

- (PullNotifyResults*) defaultInstance;

- (PullNotifyResults_Builder*) clear;
- (PullNotifyResults_Builder*) clone;

- (PullNotifyResults*) build;
- (PullNotifyResults*) buildPartial;

- (PullNotifyResults_Builder*) mergeFrom:(PullNotifyResults*) other;
- (PullNotifyResults_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PullNotifyResults_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatusCode;
- (int32_t) statusCode;
- (PullNotifyResults_Builder*) setStatusCode:(int32_t) value;
- (PullNotifyResults_Builder*) clearStatusCode;

- (NSArray*) argsListList;
- (PullNotifyResults_NotifyMsgSArgs*) argsListAtIndex:(int32_t) index;
- (PullNotifyResults_Builder*) replaceArgsListAtIndex:(int32_t) index with:(PullNotifyResults_NotifyMsgSArgs*) value;
- (PullNotifyResults_Builder*) addArgsList:(PullNotifyResults_NotifyMsgSArgs*) value;
- (PullNotifyResults_Builder*) addAllArgsList:(NSArray*) values;
- (PullNotifyResults_Builder*) clearArgsListList;

- (BOOL) hasIsCompleted;
- (BOOL) isCompleted;
- (PullNotifyResults_Builder*) setIsCompleted:(BOOL) value;
- (PullNotifyResults_Builder*) clearIsCompleted;

- (BOOL) hasSyncId;
- (int64_t) syncId;
- (PullNotifyResults_Builder*) setSyncId:(int64_t) value;
- (PullNotifyResults_Builder*) clearSyncId;
@end

