// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "DelMsgReqArgs.pb.h"

@implementation DelMsgReqArgsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [DelMsgReqArgsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface DelMsgReqArgs ()
@property int64_t syncId;
@end

@implementation DelMsgReqArgs

- (BOOL) hasSyncId {
  return !!hasSyncId_;
}
- (void) setHasSyncId:(BOOL) value_ {
  hasSyncId_ = !!value_;
}
@synthesize syncId;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.syncId = 0L;
  }
  return self;
}
static DelMsgReqArgs* defaultDelMsgReqArgsInstance = nil;
+ (void) initialize {
  if (self == [DelMsgReqArgs class]) {
    defaultDelMsgReqArgsInstance = [[DelMsgReqArgs alloc] init];
  }
}
+ (DelMsgReqArgs*) defaultInstance {
  return defaultDelMsgReqArgsInstance;
}
- (DelMsgReqArgs*) defaultInstance {
  return defaultDelMsgReqArgsInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSyncId) {
    [output writeInt64:1 value:self.syncId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSyncId) {
    size_ += computeInt64Size(1, self.syncId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (DelMsgReqArgs*) parseFromData:(NSData*) data {
  return (DelMsgReqArgs*)[[[DelMsgReqArgs builder] mergeFromData:data] build];
}
+ (DelMsgReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DelMsgReqArgs*)[[[DelMsgReqArgs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (DelMsgReqArgs*) parseFromInputStream:(NSInputStream*) input {
  return (DelMsgReqArgs*)[[[DelMsgReqArgs builder] mergeFromInputStream:input] build];
}
+ (DelMsgReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DelMsgReqArgs*)[[[DelMsgReqArgs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DelMsgReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (DelMsgReqArgs*)[[[DelMsgReqArgs builder] mergeFromCodedInputStream:input] build];
}
+ (DelMsgReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (DelMsgReqArgs*)[[[DelMsgReqArgs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (DelMsgReqArgs_Builder*) builder {
  return [[[DelMsgReqArgs_Builder alloc] init] autorelease];
}
+ (DelMsgReqArgs_Builder*) builderWithPrototype:(DelMsgReqArgs*) prototype {
  return [[DelMsgReqArgs builder] mergeFrom:prototype];
}
- (DelMsgReqArgs_Builder*) builder {
  return [DelMsgReqArgs builder];
}
- (DelMsgReqArgs_Builder*) toBuilder {
  return [DelMsgReqArgs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSyncId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"syncId", [NSNumber numberWithLongLong:self.syncId]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[DelMsgReqArgs class]]) {
    return NO;
  }
  DelMsgReqArgs *otherMessage = other;
  return
      self.hasSyncId == otherMessage.hasSyncId &&
      (!self.hasSyncId || self.syncId == otherMessage.syncId) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasSyncId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.syncId] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface DelMsgReqArgs_Builder()
@property (retain) DelMsgReqArgs* result;
@end

@implementation DelMsgReqArgs_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[DelMsgReqArgs alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (DelMsgReqArgs_Builder*) clear {
  self.result = [[[DelMsgReqArgs alloc] init] autorelease];
  return self;
}
- (DelMsgReqArgs_Builder*) clone {
  return [DelMsgReqArgs builderWithPrototype:result];
}
- (DelMsgReqArgs*) defaultInstance {
  return [DelMsgReqArgs defaultInstance];
}
- (DelMsgReqArgs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (DelMsgReqArgs*) buildPartial {
  DelMsgReqArgs* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (DelMsgReqArgs_Builder*) mergeFrom:(DelMsgReqArgs*) other {
  if (other == [DelMsgReqArgs defaultInstance]) {
    return self;
  }
  if (other.hasSyncId) {
    [self setSyncId:other.syncId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (DelMsgReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (DelMsgReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setSyncId:[input readInt64]];
        break;
      }
    }
  }
}
- (BOOL) hasSyncId {
  return result.hasSyncId;
}
- (int64_t) syncId {
  return result.syncId;
}
- (DelMsgReqArgs_Builder*) setSyncId:(int64_t) value {
  result.hasSyncId = YES;
  result.syncId = value;
  return self;
}
- (DelMsgReqArgs_Builder*) clearSyncId {
  result.hasSyncId = NO;
  result.syncId = 0L;
  return self;
}
@end

