// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class SendMsgReqArgs;
@class SendMsgReqArgsBuilder;
@class SendMsgReqArgsMsgEntity;
@class SendMsgReqArgsMsgEntityBuilder;



@interface SendMsgReqArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SendMsgReqArgs_fromBopId @"fromBopId"
#define SendMsgReqArgs_toUserId @"toUserId"
#define SendMsgReqArgs_msg @"msg"
#define SendMsgReqArgs_sendDate @"sendDate"
#define SendMsgReqArgs_sendClientType @"sendClientType"
#define SendMsgReqArgs_sendClientPortraitUrl @"sendClientPortraitUrl"
@interface SendMsgReqArgs : PBGeneratedMessage {
@private
  BOOL hasSendClientType_:1;
  BOOL hasFromBopId_:1;
  BOOL hasToUserId_:1;
  BOOL hasSendDate_:1;
  BOOL hasSendClientPortraitUrl_:1;
  BOOL hasMsg_:1;
  SInt32 sendClientType;
  NSString* fromBopId;
  NSString* toUserId;
  NSString* sendDate;
  NSString* sendClientPortraitUrl;
  SendMsgReqArgsMsgEntity* msg;
}
- (BOOL) hasFromBopId;
- (BOOL) hasToUserId;
- (BOOL) hasMsg;
- (BOOL) hasSendDate;
- (BOOL) hasSendClientType;
- (BOOL) hasSendClientPortraitUrl;
@property (readonly, strong) NSString* fromBopId;
@property (readonly, strong) NSString* toUserId;
@property (readonly, strong) SendMsgReqArgsMsgEntity* msg;
@property (readonly, strong) NSString* sendDate;
@property (readonly) SInt32 sendClientType;
@property (readonly, strong) NSString* sendClientPortraitUrl;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SendMsgReqArgsBuilder*) builder;
+ (SendMsgReqArgsBuilder*) builder;
+ (SendMsgReqArgsBuilder*) builderWithPrototype:(SendMsgReqArgs*) prototype;
- (SendMsgReqArgsBuilder*) toBuilder;

+ (SendMsgReqArgs*) parseFromData:(NSData*) data;
+ (SendMsgReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMsgReqArgs*) parseFromInputStream:(NSInputStream*) input;
+ (SendMsgReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMsgReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SendMsgReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define MsgEntity_msgId @"msgId"
#define MsgEntity_syncId @"syncId"
#define MsgEntity_msgType @"msgType"
#define MsgEntity_msgAttribute @"msgAttribute"
#define MsgEntity_msgContent @"msgContent"
#define MsgEntity_senderNickname @"senderNickname"
#define MsgEntity_senderId @"senderId"
#define MsgEntity_extend @"extend"
#define MsgEntity_pushDesc @"pushDesc"
@interface SendMsgReqArgsMsgEntity : PBGeneratedMessage {
@private
  BOOL hasSyncId_:1;
  BOOL hasMsgId_:1;
  BOOL hasMsgType_:1;
  BOOL hasMsgAttribute_:1;
  BOOL hasMsgContent_:1;
  BOOL hasSenderNickname_:1;
  BOOL hasSenderId_:1;
  BOOL hasPushDesc_:1;
  BOOL hasExtend_:1;
  SInt64 syncId;
  NSString* msgId;
  NSString* msgType;
  NSString* msgAttribute;
  NSString* msgContent;
  NSString* senderNickname;
  NSString* senderId;
  NSString* pushDesc;
  NSData* extend;
}
- (BOOL) hasMsgId;
- (BOOL) hasSyncId;
- (BOOL) hasMsgType;
- (BOOL) hasMsgAttribute;
- (BOOL) hasMsgContent;
- (BOOL) hasSenderNickname;
- (BOOL) hasSenderId;
- (BOOL) hasExtend;
- (BOOL) hasPushDesc;
@property (readonly, strong) NSString* msgId;
@property (readonly) SInt64 syncId;
@property (readonly, strong) NSString* msgType;
@property (readonly, strong) NSString* msgAttribute;
@property (readonly, strong) NSString* msgContent;
@property (readonly, strong) NSString* senderNickname;
@property (readonly, strong) NSString* senderId;
@property (readonly, strong) NSData* extend;
@property (readonly, strong) NSString* pushDesc;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SendMsgReqArgsMsgEntityBuilder*) builder;
+ (SendMsgReqArgsMsgEntityBuilder*) builder;
+ (SendMsgReqArgsMsgEntityBuilder*) builderWithPrototype:(SendMsgReqArgsMsgEntity*) prototype;
- (SendMsgReqArgsMsgEntityBuilder*) toBuilder;

+ (SendMsgReqArgsMsgEntity*) parseFromData:(NSData*) data;
+ (SendMsgReqArgsMsgEntity*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMsgReqArgsMsgEntity*) parseFromInputStream:(NSInputStream*) input;
+ (SendMsgReqArgsMsgEntity*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SendMsgReqArgsMsgEntity*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SendMsgReqArgsMsgEntity*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SendMsgReqArgsMsgEntityBuilder : PBGeneratedMessage_Builder {
@private
  SendMsgReqArgsMsgEntity* resultMsgEntity;
}

- (SendMsgReqArgsMsgEntity*) defaultInstance;

- (SendMsgReqArgsMsgEntityBuilder*) clear;
- (SendMsgReqArgsMsgEntityBuilder*) clone;

- (SendMsgReqArgsMsgEntity*) build;
- (SendMsgReqArgsMsgEntity*) buildPartial;

- (SendMsgReqArgsMsgEntityBuilder*) mergeFrom:(SendMsgReqArgsMsgEntity*) other;
- (SendMsgReqArgsMsgEntityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SendMsgReqArgsMsgEntityBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMsgId;
- (NSString*) msgId;
- (SendMsgReqArgsMsgEntityBuilder*) setMsgId:(NSString*) value;
- (SendMsgReqArgsMsgEntityBuilder*) clearMsgId;

- (BOOL) hasSyncId;
- (SInt64) syncId;
- (SendMsgReqArgsMsgEntityBuilder*) setSyncId:(SInt64) value;
- (SendMsgReqArgsMsgEntityBuilder*) clearSyncId;

- (BOOL) hasMsgType;
- (NSString*) msgType;
- (SendMsgReqArgsMsgEntityBuilder*) setMsgType:(NSString*) value;
- (SendMsgReqArgsMsgEntityBuilder*) clearMsgType;

- (BOOL) hasMsgAttribute;
- (NSString*) msgAttribute;
- (SendMsgReqArgsMsgEntityBuilder*) setMsgAttribute:(NSString*) value;
- (SendMsgReqArgsMsgEntityBuilder*) clearMsgAttribute;

- (BOOL) hasMsgContent;
- (NSString*) msgContent;
- (SendMsgReqArgsMsgEntityBuilder*) setMsgContent:(NSString*) value;
- (SendMsgReqArgsMsgEntityBuilder*) clearMsgContent;

- (BOOL) hasSenderNickname;
- (NSString*) senderNickname;
- (SendMsgReqArgsMsgEntityBuilder*) setSenderNickname:(NSString*) value;
- (SendMsgReqArgsMsgEntityBuilder*) clearSenderNickname;

- (BOOL) hasSenderId;
- (NSString*) senderId;
- (SendMsgReqArgsMsgEntityBuilder*) setSenderId:(NSString*) value;
- (SendMsgReqArgsMsgEntityBuilder*) clearSenderId;

- (BOOL) hasExtend;
- (NSData*) extend;
- (SendMsgReqArgsMsgEntityBuilder*) setExtend:(NSData*) value;
- (SendMsgReqArgsMsgEntityBuilder*) clearExtend;

- (BOOL) hasPushDesc;
- (NSString*) pushDesc;
- (SendMsgReqArgsMsgEntityBuilder*) setPushDesc:(NSString*) value;
- (SendMsgReqArgsMsgEntityBuilder*) clearPushDesc;
@end

@interface SendMsgReqArgsBuilder : PBGeneratedMessage_Builder {
@private
  SendMsgReqArgs* resultSendMsgReqArgs;
}

- (SendMsgReqArgs*) defaultInstance;

- (SendMsgReqArgsBuilder*) clear;
- (SendMsgReqArgsBuilder*) clone;

- (SendMsgReqArgs*) build;
- (SendMsgReqArgs*) buildPartial;

- (SendMsgReqArgsBuilder*) mergeFrom:(SendMsgReqArgs*) other;
- (SendMsgReqArgsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SendMsgReqArgsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasFromBopId;
- (NSString*) fromBopId;
- (SendMsgReqArgsBuilder*) setFromBopId:(NSString*) value;
- (SendMsgReqArgsBuilder*) clearFromBopId;

- (BOOL) hasToUserId;
- (NSString*) toUserId;
- (SendMsgReqArgsBuilder*) setToUserId:(NSString*) value;
- (SendMsgReqArgsBuilder*) clearToUserId;

- (BOOL) hasMsg;
- (SendMsgReqArgsMsgEntity*) msg;
- (SendMsgReqArgsBuilder*) setMsg:(SendMsgReqArgsMsgEntity*) value;
- (SendMsgReqArgsBuilder*) setMsgBuilder:(SendMsgReqArgsMsgEntityBuilder*) builderForValue;
- (SendMsgReqArgsBuilder*) mergeMsg:(SendMsgReqArgsMsgEntity*) value;
- (SendMsgReqArgsBuilder*) clearMsg;

- (BOOL) hasSendDate;
- (NSString*) sendDate;
- (SendMsgReqArgsBuilder*) setSendDate:(NSString*) value;
- (SendMsgReqArgsBuilder*) clearSendDate;

- (BOOL) hasSendClientType;
- (SInt32) sendClientType;
- (SendMsgReqArgsBuilder*) setSendClientType:(SInt32) value;
- (SendMsgReqArgsBuilder*) clearSendClientType;

- (BOOL) hasSendClientPortraitUrl;
- (NSString*) sendClientPortraitUrl;
- (SendMsgReqArgsBuilder*) setSendClientPortraitUrl:(NSString*) value;
- (SendMsgReqArgsBuilder*) clearSendClientPortraitUrl;
@end


// @@protoc_insertion_point(global_scope)
