// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class GetSmsCodeRspRets;
@class GetSmsCodeRspRets_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface GetSmsCodeRspRetsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GetSmsCodeRspRets : PBGeneratedMessage {
@private
  BOOL hasRetCode_:1;
  BOOL hasSmsKey_:1;
  BOOL hasSmsValue_:1;
  int32_t retCode;
  NSString* smsKey;
  NSString* smsValue;
}
- (BOOL) hasRetCode;
- (BOOL) hasSmsKey;
- (BOOL) hasSmsValue;
@property (readonly) int32_t retCode;
@property (readonly, retain) NSString* smsKey;
@property (readonly, retain) NSString* smsValue;

+ (GetSmsCodeRspRets*) defaultInstance;
- (GetSmsCodeRspRets*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetSmsCodeRspRets_Builder*) builder;
+ (GetSmsCodeRspRets_Builder*) builder;
+ (GetSmsCodeRspRets_Builder*) builderWithPrototype:(GetSmsCodeRspRets*) prototype;
- (GetSmsCodeRspRets_Builder*) toBuilder;

+ (GetSmsCodeRspRets*) parseFromData:(NSData*) data;
+ (GetSmsCodeRspRets*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetSmsCodeRspRets*) parseFromInputStream:(NSInputStream*) input;
+ (GetSmsCodeRspRets*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetSmsCodeRspRets*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetSmsCodeRspRets*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetSmsCodeRspRets_Builder : PBGeneratedMessage_Builder {
@private
  GetSmsCodeRspRets* result;
}

- (GetSmsCodeRspRets*) defaultInstance;

- (GetSmsCodeRspRets_Builder*) clear;
- (GetSmsCodeRspRets_Builder*) clone;

- (GetSmsCodeRspRets*) build;
- (GetSmsCodeRspRets*) buildPartial;

- (GetSmsCodeRspRets_Builder*) mergeFrom:(GetSmsCodeRspRets*) other;
- (GetSmsCodeRspRets_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetSmsCodeRspRets_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRetCode;
- (int32_t) retCode;
- (GetSmsCodeRspRets_Builder*) setRetCode:(int32_t) value;
- (GetSmsCodeRspRets_Builder*) clearRetCode;

- (BOOL) hasSmsKey;
- (NSString*) smsKey;
- (GetSmsCodeRspRets_Builder*) setSmsKey:(NSString*) value;
- (GetSmsCodeRspRets_Builder*) clearSmsKey;

- (BOOL) hasSmsValue;
- (NSString*) smsValue;
- (GetSmsCodeRspRets_Builder*) setSmsValue:(NSString*) value;
- (GetSmsCodeRspRets_Builder*) clearSmsValue;
@end

