// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MakeCertPicRspRets;
@class MakeCertPicRspRets_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface MakeCertPicRspRetsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MakeCertPicRspRets : PBGeneratedMessage {
@private
  BOOL hasRetCode_:1;
  BOOL hasPicType_:1;
  BOOL hasCertPicKey_:1;
  BOOL hasCertPicBase64Str_:1;
  BOOL hasCertPicValue_:1;
  int32_t retCode;
  int32_t picType;
  NSString* certPicKey;
  NSString* certPicBase64Str;
  NSString* certPicValue;
}
- (BOOL) hasRetCode;
- (BOOL) hasPicType;
- (BOOL) hasCertPicKey;
- (BOOL) hasCertPicBase64Str;
- (BOOL) hasCertPicValue;
@property (readonly) int32_t retCode;
@property (readonly) int32_t picType;
@property (readonly, retain) NSString* certPicKey;
@property (readonly, retain) NSString* certPicBase64Str;
@property (readonly, retain) NSString* certPicValue;

+ (MakeCertPicRspRets*) defaultInstance;
- (MakeCertPicRspRets*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MakeCertPicRspRets_Builder*) builder;
+ (MakeCertPicRspRets_Builder*) builder;
+ (MakeCertPicRspRets_Builder*) builderWithPrototype:(MakeCertPicRspRets*) prototype;
- (MakeCertPicRspRets_Builder*) toBuilder;

+ (MakeCertPicRspRets*) parseFromData:(NSData*) data;
+ (MakeCertPicRspRets*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MakeCertPicRspRets*) parseFromInputStream:(NSInputStream*) input;
+ (MakeCertPicRspRets*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MakeCertPicRspRets*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MakeCertPicRspRets*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MakeCertPicRspRets_Builder : PBGeneratedMessage_Builder {
@private
  MakeCertPicRspRets* result;
}

- (MakeCertPicRspRets*) defaultInstance;

- (MakeCertPicRspRets_Builder*) clear;
- (MakeCertPicRspRets_Builder*) clone;

- (MakeCertPicRspRets*) build;
- (MakeCertPicRspRets*) buildPartial;

- (MakeCertPicRspRets_Builder*) mergeFrom:(MakeCertPicRspRets*) other;
- (MakeCertPicRspRets_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MakeCertPicRspRets_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRetCode;
- (int32_t) retCode;
- (MakeCertPicRspRets_Builder*) setRetCode:(int32_t) value;
- (MakeCertPicRspRets_Builder*) clearRetCode;

- (BOOL) hasPicType;
- (int32_t) picType;
- (MakeCertPicRspRets_Builder*) setPicType:(int32_t) value;
- (MakeCertPicRspRets_Builder*) clearPicType;

- (BOOL) hasCertPicKey;
- (NSString*) certPicKey;
- (MakeCertPicRspRets_Builder*) setCertPicKey:(NSString*) value;
- (MakeCertPicRspRets_Builder*) clearCertPicKey;

- (BOOL) hasCertPicBase64Str;
- (NSString*) certPicBase64Str;
- (MakeCertPicRspRets_Builder*) setCertPicBase64Str:(NSString*) value;
- (MakeCertPicRspRets_Builder*) clearCertPicBase64Str;

- (BOOL) hasCertPicValue;
- (NSString*) certPicValue;
- (MakeCertPicRspRets_Builder*) setCertPicValue:(NSString*) value;
- (MakeCertPicRspRets_Builder*) clearCertPicValue;
@end

