// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ResetPwdRspRets;
@class ResetPwdRspRets_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface ResetPwdRspRetsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ResetPwdRspRets : PBGeneratedMessage {
@private
  BOOL hasRetCode_:1;
  BOOL hasNewPwd_:1;
  int32_t retCode;
  NSString* newPwd;
}
- (BOOL) hasRetCode;
- (BOOL) hasNewPwd;
@property (readonly) int32_t retCode;
@property (readonly, retain) NS_RETURNS_NOT_RETAINED NSString* newPwd;

+ (ResetPwdRspRets*) defaultInstance;
- (ResetPwdRspRets*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResetPwdRspRets_Builder*) builder;
+ (ResetPwdRspRets_Builder*) builder;
+ (ResetPwdRspRets_Builder*) builderWithPrototype:(ResetPwdRspRets*) prototype;
- (ResetPwdRspRets_Builder*) toBuilder;

+ (ResetPwdRspRets*) parseFromData:(NSData*) data;
+ (ResetPwdRspRets*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResetPwdRspRets*) parseFromInputStream:(NSInputStream*) input;
+ (ResetPwdRspRets*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResetPwdRspRets*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResetPwdRspRets*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResetPwdRspRets_Builder : PBGeneratedMessage_Builder {
@private
  ResetPwdRspRets* result;
}

- (ResetPwdRspRets*) defaultInstance;

- (ResetPwdRspRets_Builder*) clear;
- (ResetPwdRspRets_Builder*) clone;

- (ResetPwdRspRets*) build;
- (ResetPwdRspRets*) buildPartial;

- (ResetPwdRspRets_Builder*) mergeFrom:(ResetPwdRspRets*) other;
- (ResetPwdRspRets_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResetPwdRspRets_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRetCode;
- (int32_t) retCode;
- (ResetPwdRspRets_Builder*) setRetCode:(int32_t) value;
- (ResetPwdRspRets_Builder*) clearRetCode;

- (BOOL) hasNewPwd;
- (NSString*) newPwd NS_RETURNS_NOT_RETAINED;
- (ResetPwdRspRets_Builder*) setNewPwd:(NSString*) value;
- (ResetPwdRspRets_Builder*) clearNewPwd;
@end

