// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class BNKickNotifyArgs;
@class BNKickNotifyArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface BnkickNotifyArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface BNKickNotifyArgs : PBGeneratedMessage {
@private
  BOOL hasClientType_:1;
  BOOL hasEventType_:1;
  BOOL hasNotifyDesc_:1;
  BOOL hasClientVersion_:1;
  int32_t clientType;
  NSString* eventType;
  NSString* notifyDesc;
  NSString* clientVersion;
}
- (BOOL) hasEventType;
- (BOOL) hasNotifyDesc;
- (BOOL) hasClientType;
- (BOOL) hasClientVersion;
@property (readonly, retain) NSString* eventType;
@property (readonly, retain) NSString* notifyDesc;
@property (readonly) int32_t clientType;
@property (readonly, retain) NSString* clientVersion;

+ (BNKickNotifyArgs*) defaultInstance;
- (BNKickNotifyArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BNKickNotifyArgs_Builder*) builder;
+ (BNKickNotifyArgs_Builder*) builder;
+ (BNKickNotifyArgs_Builder*) builderWithPrototype:(BNKickNotifyArgs*) prototype;
- (BNKickNotifyArgs_Builder*) toBuilder;

+ (BNKickNotifyArgs*) parseFromData:(NSData*) data;
+ (BNKickNotifyArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BNKickNotifyArgs*) parseFromInputStream:(NSInputStream*) input;
+ (BNKickNotifyArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BNKickNotifyArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BNKickNotifyArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BNKickNotifyArgs_Builder : PBGeneratedMessage_Builder {
@private
  BNKickNotifyArgs* result;
}

- (BNKickNotifyArgs*) defaultInstance;

- (BNKickNotifyArgs_Builder*) clear;
- (BNKickNotifyArgs_Builder*) clone;

- (BNKickNotifyArgs*) build;
- (BNKickNotifyArgs*) buildPartial;

- (BNKickNotifyArgs_Builder*) mergeFrom:(BNKickNotifyArgs*) other;
- (BNKickNotifyArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BNKickNotifyArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEventType;
- (NSString*) eventType;
- (BNKickNotifyArgs_Builder*) setEventType:(NSString*) value;
- (BNKickNotifyArgs_Builder*) clearEventType;

- (BOOL) hasNotifyDesc;
- (NSString*) notifyDesc;
- (BNKickNotifyArgs_Builder*) setNotifyDesc:(NSString*) value;
- (BNKickNotifyArgs_Builder*) clearNotifyDesc;

- (BOOL) hasClientType;
- (int32_t) clientType;
- (BNKickNotifyArgs_Builder*) setClientType:(int32_t) value;
- (BNKickNotifyArgs_Builder*) clearClientType;

- (BOOL) hasClientVersion;
- (NSString*) clientVersion;
- (BNKickNotifyArgs_Builder*) setClientVersion:(NSString*) value;
- (BNKickNotifyArgs_Builder*) clearClientVersion;
@end

