// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "KeepAliveArgs.pb.h"

@implementation KeepAliveArgsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [KeepAliveArgsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface KeepAliveArgs ()
@property int64_t sysMsgId;
@end

@implementation KeepAliveArgs

- (BOOL) hasSysMsgId {
  return !!hasSysMsgId_;
}
- (void) setHasSysMsgId:(BOOL) value_ {
  hasSysMsgId_ = !!value_;
}
@synthesize sysMsgId;
- (void) dealloc {
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.sysMsgId = 0L;
  }
  return self;
}
static KeepAliveArgs* defaultKeepAliveArgsInstance = nil;
+ (void) initialize {
  if (self == [KeepAliveArgs class]) {
    defaultKeepAliveArgsInstance = [[KeepAliveArgs alloc] init];
  }
}
+ (KeepAliveArgs*) defaultInstance {
  return defaultKeepAliveArgsInstance;
}
- (KeepAliveArgs*) defaultInstance {
  return defaultKeepAliveArgsInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasSysMsgId) {
    [output writeInt64:1 value:self.sysMsgId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasSysMsgId) {
    size_ += computeInt64Size(1, self.sysMsgId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (KeepAliveArgs*) parseFromData:(NSData*) data {
  return (KeepAliveArgs*)[[[KeepAliveArgs builder] mergeFromData:data] build];
}
+ (KeepAliveArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (KeepAliveArgs*)[[[KeepAliveArgs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (KeepAliveArgs*) parseFromInputStream:(NSInputStream*) input {
  return (KeepAliveArgs*)[[[KeepAliveArgs builder] mergeFromInputStream:input] build];
}
+ (KeepAliveArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (KeepAliveArgs*)[[[KeepAliveArgs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (KeepAliveArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (KeepAliveArgs*)[[[KeepAliveArgs builder] mergeFromCodedInputStream:input] build];
}
+ (KeepAliveArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (KeepAliveArgs*)[[[KeepAliveArgs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (KeepAliveArgs_Builder*) builder {
  return [[[KeepAliveArgs_Builder alloc] init] autorelease];
}
+ (KeepAliveArgs_Builder*) builderWithPrototype:(KeepAliveArgs*) prototype {
  return [[KeepAliveArgs builder] mergeFrom:prototype];
}
- (KeepAliveArgs_Builder*) builder {
  return [KeepAliveArgs builder];
}
- (KeepAliveArgs_Builder*) toBuilder {
  return [KeepAliveArgs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasSysMsgId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"sysMsgId", [NSNumber numberWithLongLong:self.sysMsgId]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[KeepAliveArgs class]]) {
    return NO;
  }
  KeepAliveArgs *otherMessage = other;
  return
      self.hasSysMsgId == otherMessage.hasSysMsgId &&
      (!self.hasSysMsgId || self.sysMsgId == otherMessage.sysMsgId) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasSysMsgId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.sysMsgId] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface KeepAliveArgs_Builder()
@property (retain) KeepAliveArgs* result;
@end

@implementation KeepAliveArgs_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[KeepAliveArgs alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (KeepAliveArgs_Builder*) clear {
  self.result = [[[KeepAliveArgs alloc] init] autorelease];
  return self;
}
- (KeepAliveArgs_Builder*) clone {
  return [KeepAliveArgs builderWithPrototype:result];
}
- (KeepAliveArgs*) defaultInstance {
  return [KeepAliveArgs defaultInstance];
}
- (KeepAliveArgs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (KeepAliveArgs*) buildPartial {
  KeepAliveArgs* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (KeepAliveArgs_Builder*) mergeFrom:(KeepAliveArgs*) other {
  if (other == [KeepAliveArgs defaultInstance]) {
    return self;
  }
  if (other.hasSysMsgId) {
    [self setSysMsgId:other.sysMsgId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (KeepAliveArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (KeepAliveArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setSysMsgId:[input readInt64]];
        break;
      }
    }
  }
}
- (BOOL) hasSysMsgId {
  return result.hasSysMsgId;
}
- (int64_t) sysMsgId {
  return result.sysMsgId;
}
- (KeepAliveArgs_Builder*) setSysMsgId:(int64_t) value {
  result.hasSysMsgId = YES;
  result.sysMsgId = value;
  return self;
}
- (KeepAliveArgs_Builder*) clearSysMsgId {
  result.hasSysMsgId = NO;
  result.sysMsgId = 0L;
  return self;
}
@end

