// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class KeepAliveResult;
@class KeepAliveResult_Builder;



@interface KeepAliveResultRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define KeepAliveResult_statusCode @"statusCode"
#define KeepAliveResult_credencial @"credencial"
@interface KeepAliveResult : PBGeneratedMessage {
@private
  BOOL hasStatusCode_:1;
  BOOL hasCredencial_:1;
  SInt32 statusCode;
  NSString* credencial;
}
- (BOOL) hasStatusCode;
- (BOOL) hasCredencial;
@property (readonly) SInt32 statusCode;
@property (readonly, strong) NSString* credencial;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (KeepAliveResult_Builder*) builder;
+ (KeepAliveResult_Builder*) builder;
+ (KeepAliveResult_Builder*) builderWithPrototype:(KeepAliveResult*) prototype;
- (KeepAliveResult_Builder*) toBuilder;

+ (KeepAliveResult*) parseFromData:(NSData*) data;
+ (KeepAliveResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (KeepAliveResult*) parseFromInputStream:(NSInputStream*) input;
+ (KeepAliveResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (KeepAliveResult*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (KeepAliveResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface KeepAliveResult_Builder : PBGeneratedMessage_Builder {
@private
  KeepAliveResult* resultKeepAliveResult;
}

- (KeepAliveResult*) defaultInstance;

- (KeepAliveResult_Builder*) clear;
- (KeepAliveResult_Builder*) clone;

- (KeepAliveResult*) build;
- (KeepAliveResult*) buildPartial;

- (KeepAliveResult_Builder*) mergeFrom:(KeepAliveResult*) other;
- (KeepAliveResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (KeepAliveResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatusCode;
- (SInt32) statusCode;
- (KeepAliveResult_Builder*) setStatusCode:(SInt32) value;
- (KeepAliveResult_Builder*) clearStatusCode;

- (BOOL) hasCredencial;
- (NSString*) credencial;
- (KeepAliveResult_Builder*) setCredencial:(NSString*) value;
- (KeepAliveResult_Builder*) clearCredencial;
@end


// @@protoc_insertion_point(global_scope)
