// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ModifyPwdReqArgs;
@class ModifyPwdReqArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface ModifyPwdReqArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ModifyPwdReqArgs : PBGeneratedMessage {
@private
  BOOL hasRegType_:1;
  BOOL hasRegValue_:1;
  BOOL hasPasswd_:1;
  int32_t regType;
  NSString* regValue;
  NSString* passwd;
}
- (BOOL) hasRegType;
- (BOOL) hasRegValue;
- (BOOL) hasPasswd;
@property (readonly) int32_t regType;
@property (readonly, retain) NSString* regValue;
@property (readonly, retain) NSString* passwd;

+ (ModifyPwdReqArgs*) defaultInstance;
- (ModifyPwdReqArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ModifyPwdReqArgs_Builder*) builder;
+ (ModifyPwdReqArgs_Builder*) builder;
+ (ModifyPwdReqArgs_Builder*) builderWithPrototype:(ModifyPwdReqArgs*) prototype;
- (ModifyPwdReqArgs_Builder*) toBuilder;

+ (ModifyPwdReqArgs*) parseFromData:(NSData*) data;
+ (ModifyPwdReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ModifyPwdReqArgs*) parseFromInputStream:(NSInputStream*) input;
+ (ModifyPwdReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ModifyPwdReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ModifyPwdReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ModifyPwdReqArgs_Builder : PBGeneratedMessage_Builder {
@private
  ModifyPwdReqArgs* result;
}

- (ModifyPwdReqArgs*) defaultInstance;

- (ModifyPwdReqArgs_Builder*) clear;
- (ModifyPwdReqArgs_Builder*) clone;

- (ModifyPwdReqArgs*) build;
- (ModifyPwdReqArgs*) buildPartial;

- (ModifyPwdReqArgs_Builder*) mergeFrom:(ModifyPwdReqArgs*) other;
- (ModifyPwdReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ModifyPwdReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRegType;
- (int32_t) regType;
- (ModifyPwdReqArgs_Builder*) setRegType:(int32_t) value;
- (ModifyPwdReqArgs_Builder*) clearRegType;

- (BOOL) hasRegValue;
- (NSString*) regValue;
- (ModifyPwdReqArgs_Builder*) setRegValue:(NSString*) value;
- (ModifyPwdReqArgs_Builder*) clearRegValue;

- (BOOL) hasPasswd;
- (NSString*) passwd;
- (ModifyPwdReqArgs_Builder*) setPasswd:(NSString*) value;
- (ModifyPwdReqArgs_Builder*) clearPasswd;
@end

