// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class ResetPwdReqArgs;
@class ResetPwdReqArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface ResetPwdReqArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface ResetPwdReqArgs : PBGeneratedMessage {
@private
  BOOL hasRegType_:1;
  BOOL hasRegValue_:1;
  int32_t regType;
  NSString* regValue;
}
- (BOOL) hasRegType;
- (BOOL) hasRegValue;
@property (readonly) int32_t regType;
@property (readonly, retain) NSString* regValue;

+ (ResetPwdReqArgs*) defaultInstance;
- (ResetPwdReqArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ResetPwdReqArgs_Builder*) builder;
+ (ResetPwdReqArgs_Builder*) builder;
+ (ResetPwdReqArgs_Builder*) builderWithPrototype:(ResetPwdReqArgs*) prototype;
- (ResetPwdReqArgs_Builder*) toBuilder;

+ (ResetPwdReqArgs*) parseFromData:(NSData*) data;
+ (ResetPwdReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResetPwdReqArgs*) parseFromInputStream:(NSInputStream*) input;
+ (ResetPwdReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ResetPwdReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ResetPwdReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ResetPwdReqArgs_Builder : PBGeneratedMessage_Builder {
@private
  ResetPwdReqArgs* result;
}

- (ResetPwdReqArgs*) defaultInstance;

- (ResetPwdReqArgs_Builder*) clear;
- (ResetPwdReqArgs_Builder*) clone;

- (ResetPwdReqArgs*) build;
- (ResetPwdReqArgs*) buildPartial;

- (ResetPwdReqArgs_Builder*) mergeFrom:(ResetPwdReqArgs*) other;
- (ResetPwdReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ResetPwdReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRegType;
- (int32_t) regType;
- (ResetPwdReqArgs_Builder*) setRegType:(int32_t) value;
- (ResetPwdReqArgs_Builder*) clearRegType;

- (BOOL) hasRegValue;
- (NSString*) regValue;
- (ResetPwdReqArgs_Builder*) setRegValue:(NSString*) value;
- (ResetPwdReqArgs_Builder*) clearRegValue;
@end

