// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ResetPwdReqArgs.pb.h"

@implementation ResetPwdReqArgsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ResetPwdReqArgsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface ResetPwdReqArgs ()
@property int32_t regType;
@property (retain) NSString* regValue;
@end

@implementation ResetPwdReqArgs

- (BOOL) hasRegType {
  return !!hasRegType_;
}
- (void) setHasRegType:(BOOL) value_ {
  hasRegType_ = !!value_;
}
@synthesize regType;
- (BOOL) hasRegValue {
  return !!hasRegValue_;
}
- (void) setHasRegValue:(BOOL) value_ {
  hasRegValue_ = !!value_;
}
@synthesize regValue;
- (void) dealloc {
  self.regValue = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.regType = 0;
    self.regValue = @"";
  }
  return self;
}
static ResetPwdReqArgs* defaultResetPwdReqArgsInstance = nil;
+ (void) initialize {
  if (self == [ResetPwdReqArgs class]) {
    defaultResetPwdReqArgsInstance = [[ResetPwdReqArgs alloc] init];
  }
}
+ (ResetPwdReqArgs*) defaultInstance {
  return defaultResetPwdReqArgsInstance;
}
- (ResetPwdReqArgs*) defaultInstance {
  return defaultResetPwdReqArgsInstance;
}
- (BOOL) isInitialized {
  if (!self.hasRegType) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasRegType) {
    [output writeInt32:1 value:self.regType];
  }
  if (self.hasRegValue) {
    [output writeString:2 value:self.regValue];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasRegType) {
    size_ += computeInt32Size(1, self.regType);
  }
  if (self.hasRegValue) {
    size_ += computeStringSize(2, self.regValue);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ResetPwdReqArgs*) parseFromData:(NSData*) data {
  return (ResetPwdReqArgs*)[[[ResetPwdReqArgs builder] mergeFromData:data] build];
}
+ (ResetPwdReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResetPwdReqArgs*)[[[ResetPwdReqArgs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ResetPwdReqArgs*) parseFromInputStream:(NSInputStream*) input {
  return (ResetPwdReqArgs*)[[[ResetPwdReqArgs builder] mergeFromInputStream:input] build];
}
+ (ResetPwdReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResetPwdReqArgs*)[[[ResetPwdReqArgs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResetPwdReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ResetPwdReqArgs*)[[[ResetPwdReqArgs builder] mergeFromCodedInputStream:input] build];
}
+ (ResetPwdReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ResetPwdReqArgs*)[[[ResetPwdReqArgs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ResetPwdReqArgs_Builder*) builder {
  return [[[ResetPwdReqArgs_Builder alloc] init] autorelease];
}
+ (ResetPwdReqArgs_Builder*) builderWithPrototype:(ResetPwdReqArgs*) prototype {
  return [[ResetPwdReqArgs builder] mergeFrom:prototype];
}
- (ResetPwdReqArgs_Builder*) builder {
  return [ResetPwdReqArgs builder];
}
- (ResetPwdReqArgs_Builder*) toBuilder {
  return [ResetPwdReqArgs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasRegType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"regType", [NSNumber numberWithInt:self.regType]];
  }
  if (self.hasRegValue) {
    [output appendFormat:@"%@%@: %@\n", indent, @"regValue", self.regValue];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ResetPwdReqArgs class]]) {
    return NO;
  }
  ResetPwdReqArgs *otherMessage = other;
  return
      self.hasRegType == otherMessage.hasRegType &&
      (!self.hasRegType || self.regType == otherMessage.regType) &&
      self.hasRegValue == otherMessage.hasRegValue &&
      (!self.hasRegValue || [self.regValue isEqual:otherMessage.regValue]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasRegType) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.regType] hash];
  }
  if (self.hasRegValue) {
    hashCode = hashCode * 31 + [self.regValue hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ResetPwdReqArgs_Builder()
@property (retain) ResetPwdReqArgs* result;
@end

@implementation ResetPwdReqArgs_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[ResetPwdReqArgs alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (ResetPwdReqArgs_Builder*) clear {
  self.result = [[[ResetPwdReqArgs alloc] init] autorelease];
  return self;
}
- (ResetPwdReqArgs_Builder*) clone {
  return [ResetPwdReqArgs builderWithPrototype:result];
}
- (ResetPwdReqArgs*) defaultInstance {
  return [ResetPwdReqArgs defaultInstance];
}
- (ResetPwdReqArgs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ResetPwdReqArgs*) buildPartial {
  ResetPwdReqArgs* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (ResetPwdReqArgs_Builder*) mergeFrom:(ResetPwdReqArgs*) other {
  if (other == [ResetPwdReqArgs defaultInstance]) {
    return self;
  }
  if (other.hasRegType) {
    [self setRegType:other.regType];
  }
  if (other.hasRegValue) {
    [self setRegValue:other.regValue];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ResetPwdReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ResetPwdReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setRegType:[input readInt32]];
        break;
      }
      case 18: {
        [self setRegValue:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasRegType {
  return result.hasRegType;
}
- (int32_t) regType {
  return result.regType;
}
- (ResetPwdReqArgs_Builder*) setRegType:(int32_t) value {
  result.hasRegType = YES;
  result.regType = value;
  return self;
}
- (ResetPwdReqArgs_Builder*) clearRegType {
  result.hasRegType = NO;
  result.regType = 0;
  return self;
}
- (BOOL) hasRegValue {
  return result.hasRegValue;
}
- (NSString*) regValue {
  return result.regValue;
}
- (ResetPwdReqArgs_Builder*) setRegValue:(NSString*) value {
  result.hasRegValue = YES;
  result.regValue = value;
  return self;
}
- (ResetPwdReqArgs_Builder*) clearRegValue {
  result.hasRegValue = NO;
  result.regValue = @"";
  return self;
}
@end

