// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class RtcInviteReqArgs;
@class RtcInviteReqArgs_Builder;
@class RtcInviteReqArgs_CallInfo;
@class RtcInviteReqArgs_CallInfo_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface RtcInviteReqArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface RtcInviteReqArgs : PBGeneratedMessage {
@private
  BOOL hasSdp_:1;
  BOOL hasCallInfo_:1;
  NSString* sdp;
  RtcInviteReqArgs_CallInfo* callInfo;
}
- (BOOL) hasCallInfo;
- (BOOL) hasSdp;
@property (readonly, retain) RtcInviteReqArgs_CallInfo* callInfo;
@property (readonly, retain) NSString* sdp;

+ (RtcInviteReqArgs*) defaultInstance;
- (RtcInviteReqArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RtcInviteReqArgs_Builder*) builder;
+ (RtcInviteReqArgs_Builder*) builder;
+ (RtcInviteReqArgs_Builder*) builderWithPrototype:(RtcInviteReqArgs*) prototype;
- (RtcInviteReqArgs_Builder*) toBuilder;

+ (RtcInviteReqArgs*) parseFromData:(NSData*) data;
+ (RtcInviteReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RtcInviteReqArgs*) parseFromInputStream:(NSInputStream*) input;
+ (RtcInviteReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RtcInviteReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RtcInviteReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RtcInviteReqArgs_CallInfo : PBGeneratedMessage {
@private
  BOOL hasPeerUserId_:1;
  BOOL hasCallId_:1;
  NSString* peerUserId;
  NSString* callId;
}
- (BOOL) hasPeerUserId;
- (BOOL) hasCallId;
@property (readonly, retain) NSString* peerUserId;
@property (readonly, retain) NSString* callId;

+ (RtcInviteReqArgs_CallInfo*) defaultInstance;
- (RtcInviteReqArgs_CallInfo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RtcInviteReqArgs_CallInfo_Builder*) builder;
+ (RtcInviteReqArgs_CallInfo_Builder*) builder;
+ (RtcInviteReqArgs_CallInfo_Builder*) builderWithPrototype:(RtcInviteReqArgs_CallInfo*) prototype;
- (RtcInviteReqArgs_CallInfo_Builder*) toBuilder;

+ (RtcInviteReqArgs_CallInfo*) parseFromData:(NSData*) data;
+ (RtcInviteReqArgs_CallInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RtcInviteReqArgs_CallInfo*) parseFromInputStream:(NSInputStream*) input;
+ (RtcInviteReqArgs_CallInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RtcInviteReqArgs_CallInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RtcInviteReqArgs_CallInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RtcInviteReqArgs_CallInfo_Builder : PBGeneratedMessage_Builder {
@private
  RtcInviteReqArgs_CallInfo* result;
}

- (RtcInviteReqArgs_CallInfo*) defaultInstance;

- (RtcInviteReqArgs_CallInfo_Builder*) clear;
- (RtcInviteReqArgs_CallInfo_Builder*) clone;

- (RtcInviteReqArgs_CallInfo*) build;
- (RtcInviteReqArgs_CallInfo*) buildPartial;

- (RtcInviteReqArgs_CallInfo_Builder*) mergeFrom:(RtcInviteReqArgs_CallInfo*) other;
- (RtcInviteReqArgs_CallInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RtcInviteReqArgs_CallInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPeerUserId;
- (NSString*) peerUserId;
- (RtcInviteReqArgs_CallInfo_Builder*) setPeerUserId:(NSString*) value;
- (RtcInviteReqArgs_CallInfo_Builder*) clearPeerUserId;

- (BOOL) hasCallId;
- (NSString*) callId;
- (RtcInviteReqArgs_CallInfo_Builder*) setCallId:(NSString*) value;
- (RtcInviteReqArgs_CallInfo_Builder*) clearCallId;
@end

@interface RtcInviteReqArgs_Builder : PBGeneratedMessage_Builder {
@private
  RtcInviteReqArgs* result;
}

- (RtcInviteReqArgs*) defaultInstance;

- (RtcInviteReqArgs_Builder*) clear;
- (RtcInviteReqArgs_Builder*) clone;

- (RtcInviteReqArgs*) build;
- (RtcInviteReqArgs*) buildPartial;

- (RtcInviteReqArgs_Builder*) mergeFrom:(RtcInviteReqArgs*) other;
- (RtcInviteReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RtcInviteReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasCallInfo;
- (RtcInviteReqArgs_CallInfo*) callInfo;
- (RtcInviteReqArgs_Builder*) setCallInfo:(RtcInviteReqArgs_CallInfo*) value;
- (RtcInviteReqArgs_Builder*) setCallInfoBuilder:(RtcInviteReqArgs_CallInfo_Builder*) builderForValue;
- (RtcInviteReqArgs_Builder*) mergeCallInfo:(RtcInviteReqArgs_CallInfo*) value;
- (RtcInviteReqArgs_Builder*) clearCallInfo;

- (BOOL) hasSdp;
- (NSString*) sdp;
- (RtcInviteReqArgs_Builder*) setSdp:(NSString*) value;
- (RtcInviteReqArgs_Builder*) clearSdp;
@end

