// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ChangeGroupOwnerNtfArgs.pb.h"
// @@protoc_insertion_point(imports)

@implementation ChangeGroupOwnerNtfArgsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [ChangeGroupOwnerNtfArgsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface ChangeGroupOwnerNtfArgs ()
@property (strong) NSString* groupId;
@property (strong) NSString* groupName;
@property (strong) NSString* userId;
@end

@implementation ChangeGroupOwnerNtfArgs

- (BOOL) hasGroupId {
  return !!hasGroupId_;
}
- (void) setHasGroupId:(BOOL) _value_ {
  hasGroupId_ = !!_value_;
}
@synthesize groupId;
- (BOOL) hasGroupName {
  return !!hasGroupName_;
}
- (void) setHasGroupName:(BOOL) _value_ {
  hasGroupName_ = !!_value_;
}
@synthesize groupName;
- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) _value_ {
  hasUserId_ = !!_value_;
}
@synthesize userId;
- (instancetype) init {
  if ((self = [super init])) {
    self.groupId = @"";
    self.groupName = @"";
    self.userId = @"";
  }
  return self;
}
static ChangeGroupOwnerNtfArgs* defaultChangeGroupOwnerNtfArgsInstance = nil;
+ (void) initialize {
  if (self == [ChangeGroupOwnerNtfArgs class]) {
    defaultChangeGroupOwnerNtfArgsInstance = [[ChangeGroupOwnerNtfArgs alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultChangeGroupOwnerNtfArgsInstance;
}
- (instancetype) defaultInstance {
  return defaultChangeGroupOwnerNtfArgsInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasGroupId) {
    [output writeString:1 value:self.groupId];
  }
  if (self.hasGroupName) {
    [output writeString:2 value:self.groupName];
  }
  if (self.hasUserId) {
    [output writeString:3 value:self.userId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasGroupId) {
    size_ += computeStringSize(1, self.groupId);
  }
  if (self.hasGroupName) {
    size_ += computeStringSize(2, self.groupName);
  }
  if (self.hasUserId) {
    size_ += computeStringSize(3, self.userId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (ChangeGroupOwnerNtfArgs*) parseFromData:(NSData*) data {
  return (ChangeGroupOwnerNtfArgs*)[[[ChangeGroupOwnerNtfArgs builder] mergeFromData:data] build];
}
+ (ChangeGroupOwnerNtfArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ChangeGroupOwnerNtfArgs*)[[[ChangeGroupOwnerNtfArgs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (ChangeGroupOwnerNtfArgs*) parseFromInputStream:(NSInputStream*) input {
  return (ChangeGroupOwnerNtfArgs*)[[[ChangeGroupOwnerNtfArgs builder] mergeFromInputStream:input] build];
}
+ (ChangeGroupOwnerNtfArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ChangeGroupOwnerNtfArgs*)[[[ChangeGroupOwnerNtfArgs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ChangeGroupOwnerNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (ChangeGroupOwnerNtfArgs*)[[[ChangeGroupOwnerNtfArgs builder] mergeFromCodedInputStream:input] build];
}
+ (ChangeGroupOwnerNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (ChangeGroupOwnerNtfArgs*)[[[ChangeGroupOwnerNtfArgs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (ChangeGroupOwnerNtfArgs_Builder*) builder {
  return [[ChangeGroupOwnerNtfArgs_Builder alloc] init];
}
+ (ChangeGroupOwnerNtfArgs_Builder*) builderWithPrototype:(ChangeGroupOwnerNtfArgs*) prototype {
  return [[ChangeGroupOwnerNtfArgs builder] mergeFrom:prototype];
}
- (ChangeGroupOwnerNtfArgs_Builder*) builder {
  return [ChangeGroupOwnerNtfArgs builder];
}
- (ChangeGroupOwnerNtfArgs_Builder*) toBuilder {
  return [ChangeGroupOwnerNtfArgs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasGroupId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"groupId", self.groupId];
  }
  if (self.hasGroupName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"groupName", self.groupName];
  }
  if (self.hasUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userId", self.userId];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[ChangeGroupOwnerNtfArgs class]]) {
    return NO;
  }
  ChangeGroupOwnerNtfArgs *otherMessage = other;
  return
      self.hasGroupId == otherMessage.hasGroupId &&
      (!self.hasGroupId || [self.groupId isEqual:otherMessage.groupId]) &&
      self.hasGroupName == otherMessage.hasGroupName &&
      (!self.hasGroupName || [self.groupName isEqual:otherMessage.groupName]) &&
      self.hasUserId == otherMessage.hasUserId &&
      (!self.hasUserId || [self.userId isEqual:otherMessage.userId]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasGroupId) {
    hashCode = hashCode * 31 + [self.groupId hash];
  }
  if (self.hasGroupName) {
    hashCode = hashCode * 31 + [self.groupName hash];
  }
  if (self.hasUserId) {
    hashCode = hashCode * 31 + [self.userId hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface ChangeGroupOwnerNtfArgs_Builder()
@property (strong) ChangeGroupOwnerNtfArgs* resultChangeGroupOwnerNtfArgs;
@end

@implementation ChangeGroupOwnerNtfArgs_Builder
@synthesize resultChangeGroupOwnerNtfArgs;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultChangeGroupOwnerNtfArgs = [[ChangeGroupOwnerNtfArgs alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultChangeGroupOwnerNtfArgs;
}
- (ChangeGroupOwnerNtfArgs_Builder*) clear {
  self.resultChangeGroupOwnerNtfArgs = [[ChangeGroupOwnerNtfArgs alloc] init];
  return self;
}
- (ChangeGroupOwnerNtfArgs_Builder*) clone {
  return [ChangeGroupOwnerNtfArgs builderWithPrototype:resultChangeGroupOwnerNtfArgs];
}
- (ChangeGroupOwnerNtfArgs*) defaultInstance {
  return [ChangeGroupOwnerNtfArgs defaultInstance];
}
- (ChangeGroupOwnerNtfArgs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (ChangeGroupOwnerNtfArgs*) buildPartial {
  ChangeGroupOwnerNtfArgs* returnMe = resultChangeGroupOwnerNtfArgs;
  self.resultChangeGroupOwnerNtfArgs = nil;
  return returnMe;
}
- (ChangeGroupOwnerNtfArgs_Builder*) mergeFrom:(ChangeGroupOwnerNtfArgs*) other {
  if (other == [ChangeGroupOwnerNtfArgs defaultInstance]) {
    return self;
  }
  if (other.hasGroupId) {
    [self setGroupId:other.groupId];
  }
  if (other.hasGroupName) {
    [self setGroupName:other.groupName];
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (ChangeGroupOwnerNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (ChangeGroupOwnerNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setGroupId:[input readString]];
        break;
      }
      case 18: {
        [self setGroupName:[input readString]];
        break;
      }
      case 26: {
        [self setUserId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasGroupId {
  return resultChangeGroupOwnerNtfArgs.hasGroupId;
}
- (NSString*) groupId {
  return resultChangeGroupOwnerNtfArgs.groupId;
}
- (ChangeGroupOwnerNtfArgs_Builder*) setGroupId:(NSString*) value {
  resultChangeGroupOwnerNtfArgs.hasGroupId = YES;
  resultChangeGroupOwnerNtfArgs.groupId = value;
  return self;
}
- (ChangeGroupOwnerNtfArgs_Builder*) clearGroupId {
  resultChangeGroupOwnerNtfArgs.hasGroupId = NO;
  resultChangeGroupOwnerNtfArgs.groupId = @"";
  return self;
}
- (BOOL) hasGroupName {
  return resultChangeGroupOwnerNtfArgs.hasGroupName;
}
- (NSString*) groupName {
  return resultChangeGroupOwnerNtfArgs.groupName;
}
- (ChangeGroupOwnerNtfArgs_Builder*) setGroupName:(NSString*) value {
  resultChangeGroupOwnerNtfArgs.hasGroupName = YES;
  resultChangeGroupOwnerNtfArgs.groupName = value;
  return self;
}
- (ChangeGroupOwnerNtfArgs_Builder*) clearGroupName {
  resultChangeGroupOwnerNtfArgs.hasGroupName = NO;
  resultChangeGroupOwnerNtfArgs.groupName = @"";
  return self;
}
- (BOOL) hasUserId {
  return resultChangeGroupOwnerNtfArgs.hasUserId;
}
- (NSString*) userId {
  return resultChangeGroupOwnerNtfArgs.userId;
}
- (ChangeGroupOwnerNtfArgs_Builder*) setUserId:(NSString*) value {
  resultChangeGroupOwnerNtfArgs.hasUserId = YES;
  resultChangeGroupOwnerNtfArgs.userId = value;
  return self;
}
- (ChangeGroupOwnerNtfArgs_Builder*) clearUserId {
  resultChangeGroupOwnerNtfArgs.hasUserId = NO;
  resultChangeGroupOwnerNtfArgs.userId = @"";
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
