// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "CreateGroupResult.pb.h"

@implementation CreateGroupResultsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [CreateGroupResultsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface CreateGroupResult ()
@property int32_t reCode;
@property (retain) NSString* groupId;
@end

@implementation CreateGroupResult

- (BOOL) hasReCode {
  return !!hasReCode_;
}
- (void) setHasReCode:(BOOL) value_ {
  hasReCode_ = !!value_;
}
@synthesize reCode;
- (BOOL) hasGroupId {
  return !!hasGroupId_;
}
- (void) setHasGroupId:(BOOL) value_ {
  hasGroupId_ = !!value_;
}
@synthesize groupId;
- (void) dealloc {
  self.groupId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.reCode = 0;
    self.groupId = @"";
  }
  return self;
}
static CreateGroupResult* defaultCreateGroupResultInstance = nil;
+ (void) initialize {
  if (self == [CreateGroupResult class]) {
    defaultCreateGroupResultInstance = [[CreateGroupResult alloc] init];
  }
}
+ (CreateGroupResult*) defaultInstance {
  return defaultCreateGroupResultInstance;
}
- (CreateGroupResult*) defaultInstance {
  return defaultCreateGroupResultInstance;
}
- (BOOL) isInitialized {
  if (!self.hasReCode) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasReCode) {
    [output writeInt32:1 value:self.reCode];
  }
  if (self.hasGroupId) {
    [output writeString:2 value:self.groupId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasReCode) {
    size_ += computeInt32Size(1, self.reCode);
  }
  if (self.hasGroupId) {
    size_ += computeStringSize(2, self.groupId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (CreateGroupResult*) parseFromData:(NSData*) data {
  return (CreateGroupResult*)[[[CreateGroupResult builder] mergeFromData:data] build];
}
+ (CreateGroupResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateGroupResult*)[[[CreateGroupResult builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (CreateGroupResult*) parseFromInputStream:(NSInputStream*) input {
  return (CreateGroupResult*)[[[CreateGroupResult builder] mergeFromInputStream:input] build];
}
+ (CreateGroupResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateGroupResult*)[[[CreateGroupResult builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateGroupResult*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (CreateGroupResult*)[[[CreateGroupResult builder] mergeFromCodedInputStream:input] build];
}
+ (CreateGroupResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (CreateGroupResult*)[[[CreateGroupResult builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (CreateGroupResult_Builder*) builder {
  return [[[CreateGroupResult_Builder alloc] init] autorelease];
}
+ (CreateGroupResult_Builder*) builderWithPrototype:(CreateGroupResult*) prototype {
  return [[CreateGroupResult builder] mergeFrom:prototype];
}
- (CreateGroupResult_Builder*) builder {
  return [CreateGroupResult builder];
}
- (CreateGroupResult_Builder*) toBuilder {
  return [CreateGroupResult builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasReCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"reCode", [NSNumber numberWithInt:self.reCode]];
  }
  if (self.hasGroupId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"groupId", self.groupId];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[CreateGroupResult class]]) {
    return NO;
  }
  CreateGroupResult *otherMessage = other;
  return
      self.hasReCode == otherMessage.hasReCode &&
      (!self.hasReCode || self.reCode == otherMessage.reCode) &&
      self.hasGroupId == otherMessage.hasGroupId &&
      (!self.hasGroupId || [self.groupId isEqual:otherMessage.groupId]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasReCode) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.reCode] hash];
  }
  if (self.hasGroupId) {
    hashCode = hashCode * 31 + [self.groupId hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface CreateGroupResult_Builder()
@property (retain) CreateGroupResult* result;
@end

@implementation CreateGroupResult_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[CreateGroupResult alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (CreateGroupResult_Builder*) clear {
  self.result = [[[CreateGroupResult alloc] init] autorelease];
  return self;
}
- (CreateGroupResult_Builder*) clone {
  return [CreateGroupResult builderWithPrototype:result];
}
- (CreateGroupResult*) defaultInstance {
  return [CreateGroupResult defaultInstance];
}
- (CreateGroupResult*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (CreateGroupResult*) buildPartial {
  CreateGroupResult* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (CreateGroupResult_Builder*) mergeFrom:(CreateGroupResult*) other {
  if (other == [CreateGroupResult defaultInstance]) {
    return self;
  }
  if (other.hasReCode) {
    [self setReCode:other.reCode];
  }
  if (other.hasGroupId) {
    [self setGroupId:other.groupId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (CreateGroupResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (CreateGroupResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setReCode:[input readInt32]];
        break;
      }
      case 18: {
        [self setGroupId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasReCode {
  return result.hasReCode;
}
- (int32_t) reCode {
  return result.reCode;
}
- (CreateGroupResult_Builder*) setReCode:(int32_t) value {
  result.hasReCode = YES;
  result.reCode = value;
  return self;
}
- (CreateGroupResult_Builder*) clearReCode {
  result.hasReCode = NO;
  result.reCode = 0;
  return self;
}
- (BOOL) hasGroupId {
  return result.hasGroupId;
}
- (NSString*) groupId {
  return result.groupId;
}
- (CreateGroupResult_Builder*) setGroupId:(NSString*) value {
  result.hasGroupId = YES;
  result.groupId = value;
  return self;
}
- (CreateGroupResult_Builder*) clearGroupId {
  result.hasGroupId = NO;
  result.groupId = @"";
  return self;
}
@end

