// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class DelGroupArgs;
@class DelGroupArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface DelGroupArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface DelGroupArgs : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  NSString* groupId;
}
- (BOOL) hasGroupId;
@property (readonly, retain) NSString* groupId;

+ (DelGroupArgs*) defaultInstance;
- (DelGroupArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DelGroupArgs_Builder*) builder;
+ (DelGroupArgs_Builder*) builder;
+ (DelGroupArgs_Builder*) builderWithPrototype:(DelGroupArgs*) prototype;
- (DelGroupArgs_Builder*) toBuilder;

+ (DelGroupArgs*) parseFromData:(NSData*) data;
+ (DelGroupArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DelGroupArgs*) parseFromInputStream:(NSInputStream*) input;
+ (DelGroupArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DelGroupArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DelGroupArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DelGroupArgs_Builder : PBGeneratedMessage_Builder {
@private
  DelGroupArgs* result;
}

- (DelGroupArgs*) defaultInstance;

- (DelGroupArgs_Builder*) clear;
- (DelGroupArgs_Builder*) clone;

- (DelGroupArgs*) build;
- (DelGroupArgs*) buildPartial;

- (DelGroupArgs_Builder*) mergeFrom:(DelGroupArgs*) other;
- (DelGroupArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DelGroupArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (DelGroupArgs_Builder*) setGroupId:(NSString*) value;
- (DelGroupArgs_Builder*) clearGroupId;
@end

