// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class GroupMemberNameChangeNtfArgs;
@class GroupMemberNameChangeNtfArgs_Builder;



@interface GroupMemberNameChangeNtfArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define GroupMemberNameChangeNtfArgs_groupId @"groupId"
#define GroupMemberNameChangeNtfArgs_groupName @"groupName"
#define GroupMemberNameChangeNtfArgs_oldGroupMemberName @"oldGroupMemberName"
#define GroupMemberNameChangeNtfArgs_newGroupMemberName @"newGroupMemberName"
#define GroupMemberNameChangeNtfArgs_userId @"userId"
@interface GroupMemberNameChangeNtfArgs : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  BOOL hasGroupName_:1;
  BOOL hasOldGroupMemberName_:1;
  BOOL hasNewGroupMemberName_:1;
  BOOL hasUserId_:1;
  NSString* groupId;
  NSString* groupName;
  NSString* oldGroupMemberName;
  NSString* newGroupMemberName;
  NSString* userId;
}
- (BOOL) hasGroupId;
- (BOOL) hasGroupName;
- (BOOL) hasOldGroupMemberName;
- (BOOL) hasNewGroupMemberName;
- (BOOL) hasUserId;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) NSString* groupName;
@property (readonly, strong) NSString* oldGroupMemberName;
@property (readonly, strong) NS_RETURNS_NOT_RETAINED NSString* newGroupMemberName;
@property (readonly, strong) NSString* userId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GroupMemberNameChangeNtfArgs_Builder*) builder;
+ (GroupMemberNameChangeNtfArgs_Builder*) builder;
+ (GroupMemberNameChangeNtfArgs_Builder*) builderWithPrototype:(GroupMemberNameChangeNtfArgs*) prototype;
- (GroupMemberNameChangeNtfArgs_Builder*) toBuilder;

+ (GroupMemberNameChangeNtfArgs*) parseFromData:(NSData*) data;
+ (GroupMemberNameChangeNtfArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupMemberNameChangeNtfArgs*) parseFromInputStream:(NSInputStream*) input;
+ (GroupMemberNameChangeNtfArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupMemberNameChangeNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GroupMemberNameChangeNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GroupMemberNameChangeNtfArgs_Builder : PBGeneratedMessage_Builder {
@private
  GroupMemberNameChangeNtfArgs* resultGroupMemberNameChangeNtfArgs;
}

- (GroupMemberNameChangeNtfArgs*) defaultInstance;

- (GroupMemberNameChangeNtfArgs_Builder*) clear;
- (GroupMemberNameChangeNtfArgs_Builder*) clone;

- (GroupMemberNameChangeNtfArgs*) build;
- (GroupMemberNameChangeNtfArgs*) buildPartial;

- (GroupMemberNameChangeNtfArgs_Builder*) mergeFrom:(GroupMemberNameChangeNtfArgs*) other;
- (GroupMemberNameChangeNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GroupMemberNameChangeNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (GroupMemberNameChangeNtfArgs_Builder*) setGroupId:(NSString*) value;
- (GroupMemberNameChangeNtfArgs_Builder*) clearGroupId;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (GroupMemberNameChangeNtfArgs_Builder*) setGroupName:(NSString*) value;
- (GroupMemberNameChangeNtfArgs_Builder*) clearGroupName;

- (BOOL) hasOldGroupMemberName;
- (NSString*) oldGroupMemberName;
- (GroupMemberNameChangeNtfArgs_Builder*) setOldGroupMemberName:(NSString*) value;
- (GroupMemberNameChangeNtfArgs_Builder*) clearOldGroupMemberName;

- (BOOL) hasNewGroupMemberName;
- (NSString*) newGroupMemberName NS_RETURNS_NOT_RETAINED;
- (GroupMemberNameChangeNtfArgs_Builder*) setNewGroupMemberName:(NSString*) value;
- (GroupMemberNameChangeNtfArgs_Builder*) clearNewGroupMemberName;

- (BOOL) hasUserId;
- (NSString*) userId;
- (GroupMemberNameChangeNtfArgs_Builder*) setUserId:(NSString*) value;
- (GroupMemberNameChangeNtfArgs_Builder*) clearUserId;
@end


// @@protoc_insertion_point(global_scope)
