// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class GroupMemberJoinNtArgs;
@class GroupMemberJoinNtArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface GroupMemberJoinNtArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GroupMemberJoinNtArgs : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  BOOL hasNickName_:1;
  BOOL hasUserId_:1;
  NSString* groupId;
  NSString* nickName;
  NSString* userId;
}
- (BOOL) hasGroupId;
- (BOOL) hasNickName;
- (BOOL) hasUserId;
@property (readonly, retain) NSString* groupId;
@property (readonly, retain) NSString* nickName;
@property (readonly, retain) NSString* userId;

+ (GroupMemberJoinNtArgs*) defaultInstance;
- (GroupMemberJoinNtArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GroupMemberJoinNtArgs_Builder*) builder;
+ (GroupMemberJoinNtArgs_Builder*) builder;
+ (GroupMemberJoinNtArgs_Builder*) builderWithPrototype:(GroupMemberJoinNtArgs*) prototype;
- (GroupMemberJoinNtArgs_Builder*) toBuilder;

+ (GroupMemberJoinNtArgs*) parseFromData:(NSData*) data;
+ (GroupMemberJoinNtArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupMemberJoinNtArgs*) parseFromInputStream:(NSInputStream*) input;
+ (GroupMemberJoinNtArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GroupMemberJoinNtArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GroupMemberJoinNtArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GroupMemberJoinNtArgs_Builder : PBGeneratedMessage_Builder {
@private
  GroupMemberJoinNtArgs* result;
}

- (GroupMemberJoinNtArgs*) defaultInstance;

- (GroupMemberJoinNtArgs_Builder*) clear;
- (GroupMemberJoinNtArgs_Builder*) clone;

- (GroupMemberJoinNtArgs*) build;
- (GroupMemberJoinNtArgs*) buildPartial;

- (GroupMemberJoinNtArgs_Builder*) mergeFrom:(GroupMemberJoinNtArgs*) other;
- (GroupMemberJoinNtArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GroupMemberJoinNtArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (GroupMemberJoinNtArgs_Builder*) setGroupId:(NSString*) value;
- (GroupMemberJoinNtArgs_Builder*) clearGroupId;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (GroupMemberJoinNtArgs_Builder*) setNickName:(NSString*) value;
- (GroupMemberJoinNtArgs_Builder*) clearNickName;

- (BOOL) hasUserId;
- (NSString*) userId;
- (GroupMemberJoinNtArgs_Builder*) setUserId:(NSString*) value;
- (GroupMemberJoinNtArgs_Builder*) clearUserId;
@end

