// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "RefuseInviteJoinGroupNtfArgs.pb.h"
// @@protoc_insertion_point(imports)

@implementation RefuseInviteJoinGroupNtfArgsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [RefuseInviteJoinGroupNtfArgsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface RefuseInviteJoinGroupNtfArgs ()
@property (strong) NSString* groupId;
@property (strong) NSMutableArray * refuseListArray;
@property (strong) NSString* groupName;
@end

@implementation RefuseInviteJoinGroupNtfArgs

- (BOOL) hasGroupId {
  return !!hasGroupId_;
}
- (void) setHasGroupId:(BOOL) _value_ {
  hasGroupId_ = !!_value_;
}
@synthesize groupId;
@synthesize refuseListArray;
@dynamic refuseList;
- (BOOL) hasGroupName {
  return !!hasGroupName_;
}
- (void) setHasGroupName:(BOOL) _value_ {
  hasGroupName_ = !!_value_;
}
@synthesize groupName;
- (instancetype) init {
  if ((self = [super init])) {
    self.groupId = @"";
    self.groupName = @"";
  }
  return self;
}
static RefuseInviteJoinGroupNtfArgs* defaultRefuseInviteJoinGroupNtfArgsInstance = nil;
+ (void) initialize {
  if (self == [RefuseInviteJoinGroupNtfArgs class]) {
    defaultRefuseInviteJoinGroupNtfArgsInstance = [[RefuseInviteJoinGroupNtfArgs alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultRefuseInviteJoinGroupNtfArgsInstance;
}
- (instancetype) defaultInstance {
  return defaultRefuseInviteJoinGroupNtfArgsInstance;
}
- (NSArray *)refuseList {
  return refuseListArray;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem*)refuseListAtIndex:(NSUInteger)index {
  return [refuseListArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasGroupId) {
    [output writeString:1 value:self.groupId];
  }
  [self.refuseListArray enumerateObjectsUsingBlock:^(RefuseInviteJoinGroupNtfArgs_NtfItem *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:2 value:element];
  }];
  if (self.hasGroupName) {
    [output writeString:3 value:self.groupName];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasGroupId) {
    size_ += computeStringSize(1, self.groupId);
  }
  [self.refuseListArray enumerateObjectsUsingBlock:^(RefuseInviteJoinGroupNtfArgs_NtfItem *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(2, element);
  }];
  if (self.hasGroupName) {
    size_ += computeStringSize(3, self.groupName);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (RefuseInviteJoinGroupNtfArgs*) parseFromData:(NSData*) data {
  return (RefuseInviteJoinGroupNtfArgs*)[[[RefuseInviteJoinGroupNtfArgs builder] mergeFromData:data] build];
}
+ (RefuseInviteJoinGroupNtfArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RefuseInviteJoinGroupNtfArgs*)[[[RefuseInviteJoinGroupNtfArgs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RefuseInviteJoinGroupNtfArgs*) parseFromInputStream:(NSInputStream*) input {
  return (RefuseInviteJoinGroupNtfArgs*)[[[RefuseInviteJoinGroupNtfArgs builder] mergeFromInputStream:input] build];
}
+ (RefuseInviteJoinGroupNtfArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RefuseInviteJoinGroupNtfArgs*)[[[RefuseInviteJoinGroupNtfArgs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RefuseInviteJoinGroupNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RefuseInviteJoinGroupNtfArgs*)[[[RefuseInviteJoinGroupNtfArgs builder] mergeFromCodedInputStream:input] build];
}
+ (RefuseInviteJoinGroupNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RefuseInviteJoinGroupNtfArgs*)[[[RefuseInviteJoinGroupNtfArgs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RefuseInviteJoinGroupNtfArgs_Builder*) builder {
  return [[RefuseInviteJoinGroupNtfArgs_Builder alloc] init];
}
+ (RefuseInviteJoinGroupNtfArgs_Builder*) builderWithPrototype:(RefuseInviteJoinGroupNtfArgs*) prototype {
  return [[RefuseInviteJoinGroupNtfArgs builder] mergeFrom:prototype];
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) builder {
  return [RefuseInviteJoinGroupNtfArgs builder];
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) toBuilder {
  return [RefuseInviteJoinGroupNtfArgs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasGroupId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"groupId", self.groupId];
  }
  [self.refuseListArray enumerateObjectsUsingBlock:^(RefuseInviteJoinGroupNtfArgs_NtfItem *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"refuseList"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  if (self.hasGroupName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"groupName", self.groupName];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[RefuseInviteJoinGroupNtfArgs class]]) {
    return NO;
  }
  RefuseInviteJoinGroupNtfArgs *otherMessage = other;
  return
      self.hasGroupId == otherMessage.hasGroupId &&
      (!self.hasGroupId || [self.groupId isEqual:otherMessage.groupId]) &&
      [self.refuseListArray isEqualToArray:otherMessage.refuseListArray] &&
      self.hasGroupName == otherMessage.hasGroupName &&
      (!self.hasGroupName || [self.groupName isEqual:otherMessage.groupName]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasGroupId) {
    hashCode = hashCode * 31 + [self.groupId hash];
  }
  [self.refuseListArray enumerateObjectsUsingBlock:^(RefuseInviteJoinGroupNtfArgs_NtfItem *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  if (self.hasGroupName) {
    hashCode = hashCode * 31 + [self.groupName hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface RefuseInviteJoinGroupNtfArgs_NtfItem ()
@property (strong) NSString* invitedUserId;
@property (strong) NSString* invitedUserName;
@end

@implementation RefuseInviteJoinGroupNtfArgs_NtfItem

- (BOOL) hasInvitedUserId {
  return !!hasInvitedUserId_;
}
- (void) setHasInvitedUserId:(BOOL) _value_ {
  hasInvitedUserId_ = !!_value_;
}
@synthesize invitedUserId;
- (BOOL) hasInvitedUserName {
  return !!hasInvitedUserName_;
}
- (void) setHasInvitedUserName:(BOOL) _value_ {
  hasInvitedUserName_ = !!_value_;
}
@synthesize invitedUserName;
- (instancetype) init {
  if ((self = [super init])) {
    self.invitedUserId = @"";
    self.invitedUserName = @"";
  }
  return self;
}
static RefuseInviteJoinGroupNtfArgs_NtfItem* defaultRefuseInviteJoinGroupNtfArgs_NtfItemInstance = nil;
+ (void) initialize {
  if (self == [RefuseInviteJoinGroupNtfArgs_NtfItem class]) {
    defaultRefuseInviteJoinGroupNtfArgs_NtfItemInstance = [[RefuseInviteJoinGroupNtfArgs_NtfItem alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultRefuseInviteJoinGroupNtfArgs_NtfItemInstance;
}
- (instancetype) defaultInstance {
  return defaultRefuseInviteJoinGroupNtfArgs_NtfItemInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasInvitedUserId) {
    [output writeString:1 value:self.invitedUserId];
  }
  if (self.hasInvitedUserName) {
    [output writeString:2 value:self.invitedUserName];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasInvitedUserId) {
    size_ += computeStringSize(1, self.invitedUserId);
  }
  if (self.hasInvitedUserName) {
    size_ += computeStringSize(2, self.invitedUserName);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromData:(NSData*) data {
  return (RefuseInviteJoinGroupNtfArgs_NtfItem*)[[[RefuseInviteJoinGroupNtfArgs_NtfItem builder] mergeFromData:data] build];
}
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RefuseInviteJoinGroupNtfArgs_NtfItem*)[[[RefuseInviteJoinGroupNtfArgs_NtfItem builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromInputStream:(NSInputStream*) input {
  return (RefuseInviteJoinGroupNtfArgs_NtfItem*)[[[RefuseInviteJoinGroupNtfArgs_NtfItem builder] mergeFromInputStream:input] build];
}
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RefuseInviteJoinGroupNtfArgs_NtfItem*)[[[RefuseInviteJoinGroupNtfArgs_NtfItem builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RefuseInviteJoinGroupNtfArgs_NtfItem*)[[[RefuseInviteJoinGroupNtfArgs_NtfItem builder] mergeFromCodedInputStream:input] build];
}
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RefuseInviteJoinGroupNtfArgs_NtfItem*)[[[RefuseInviteJoinGroupNtfArgs_NtfItem builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) builder {
  return [[RefuseInviteJoinGroupNtfArgs_NtfItem_Builder alloc] init];
}
+ (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) builderWithPrototype:(RefuseInviteJoinGroupNtfArgs_NtfItem*) prototype {
  return [[RefuseInviteJoinGroupNtfArgs_NtfItem builder] mergeFrom:prototype];
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) builder {
  return [RefuseInviteJoinGroupNtfArgs_NtfItem builder];
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) toBuilder {
  return [RefuseInviteJoinGroupNtfArgs_NtfItem builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasInvitedUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"invitedUserId", self.invitedUserId];
  }
  if (self.hasInvitedUserName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"invitedUserName", self.invitedUserName];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[RefuseInviteJoinGroupNtfArgs_NtfItem class]]) {
    return NO;
  }
  RefuseInviteJoinGroupNtfArgs_NtfItem *otherMessage = other;
  return
      self.hasInvitedUserId == otherMessage.hasInvitedUserId &&
      (!self.hasInvitedUserId || [self.invitedUserId isEqual:otherMessage.invitedUserId]) &&
      self.hasInvitedUserName == otherMessage.hasInvitedUserName &&
      (!self.hasInvitedUserName || [self.invitedUserName isEqual:otherMessage.invitedUserName]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasInvitedUserId) {
    hashCode = hashCode * 31 + [self.invitedUserId hash];
  }
  if (self.hasInvitedUserName) {
    hashCode = hashCode * 31 + [self.invitedUserName hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface RefuseInviteJoinGroupNtfArgs_NtfItem_Builder()
@property (strong) RefuseInviteJoinGroupNtfArgs_NtfItem* resultNtfItem;
@end

@implementation RefuseInviteJoinGroupNtfArgs_NtfItem_Builder
@synthesize resultNtfItem;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultNtfItem = [[RefuseInviteJoinGroupNtfArgs_NtfItem alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultNtfItem;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) clear {
  self.resultNtfItem = [[RefuseInviteJoinGroupNtfArgs_NtfItem alloc] init];
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) clone {
  return [RefuseInviteJoinGroupNtfArgs_NtfItem builderWithPrototype:resultNtfItem];
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem*) defaultInstance {
  return [RefuseInviteJoinGroupNtfArgs_NtfItem defaultInstance];
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem*) buildPartial {
  RefuseInviteJoinGroupNtfArgs_NtfItem* returnMe = resultNtfItem;
  self.resultNtfItem = nil;
  return returnMe;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) mergeFrom:(RefuseInviteJoinGroupNtfArgs_NtfItem*) other {
  if (other == [RefuseInviteJoinGroupNtfArgs_NtfItem defaultInstance]) {
    return self;
  }
  if (other.hasInvitedUserId) {
    [self setInvitedUserId:other.invitedUserId];
  }
  if (other.hasInvitedUserName) {
    [self setInvitedUserName:other.invitedUserName];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setInvitedUserId:[input readString]];
        break;
      }
      case 18: {
        [self setInvitedUserName:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasInvitedUserId {
  return resultNtfItem.hasInvitedUserId;
}
- (NSString*) invitedUserId {
  return resultNtfItem.invitedUserId;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) setInvitedUserId:(NSString*) value {
  resultNtfItem.hasInvitedUserId = YES;
  resultNtfItem.invitedUserId = value;
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) clearInvitedUserId {
  resultNtfItem.hasInvitedUserId = NO;
  resultNtfItem.invitedUserId = @"";
  return self;
}
- (BOOL) hasInvitedUserName {
  return resultNtfItem.hasInvitedUserName;
}
- (NSString*) invitedUserName {
  return resultNtfItem.invitedUserName;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) setInvitedUserName:(NSString*) value {
  resultNtfItem.hasInvitedUserName = YES;
  resultNtfItem.invitedUserName = value;
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) clearInvitedUserName {
  resultNtfItem.hasInvitedUserName = NO;
  resultNtfItem.invitedUserName = @"";
  return self;
}
@end

@interface RefuseInviteJoinGroupNtfArgs_Builder()
@property (strong) RefuseInviteJoinGroupNtfArgs* resultRefuseInviteJoinGroupNtfArgs;
@end

@implementation RefuseInviteJoinGroupNtfArgs_Builder
@synthesize resultRefuseInviteJoinGroupNtfArgs;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultRefuseInviteJoinGroupNtfArgs = [[RefuseInviteJoinGroupNtfArgs alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultRefuseInviteJoinGroupNtfArgs;
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) clear {
  self.resultRefuseInviteJoinGroupNtfArgs = [[RefuseInviteJoinGroupNtfArgs alloc] init];
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) clone {
  return [RefuseInviteJoinGroupNtfArgs builderWithPrototype:resultRefuseInviteJoinGroupNtfArgs];
}
- (RefuseInviteJoinGroupNtfArgs*) defaultInstance {
  return [RefuseInviteJoinGroupNtfArgs defaultInstance];
}
- (RefuseInviteJoinGroupNtfArgs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RefuseInviteJoinGroupNtfArgs*) buildPartial {
  RefuseInviteJoinGroupNtfArgs* returnMe = resultRefuseInviteJoinGroupNtfArgs;
  self.resultRefuseInviteJoinGroupNtfArgs = nil;
  return returnMe;
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) mergeFrom:(RefuseInviteJoinGroupNtfArgs*) other {
  if (other == [RefuseInviteJoinGroupNtfArgs defaultInstance]) {
    return self;
  }
  if (other.hasGroupId) {
    [self setGroupId:other.groupId];
  }
  if (other.refuseListArray.count > 0) {
    if (resultRefuseInviteJoinGroupNtfArgs.refuseListArray == nil) {
      resultRefuseInviteJoinGroupNtfArgs.refuseListArray = [[NSMutableArray alloc] initWithArray:other.refuseListArray];
    } else {
      [resultRefuseInviteJoinGroupNtfArgs.refuseListArray addObjectsFromArray:other.refuseListArray];
    }
  }
  if (other.hasGroupName) {
    [self setGroupName:other.groupName];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setGroupId:[input readString]];
        break;
      }
      case 18: {
        RefuseInviteJoinGroupNtfArgs_NtfItem_Builder* subBuilder = [RefuseInviteJoinGroupNtfArgs_NtfItem builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addRefuseList:[subBuilder buildPartial]];
        break;
      }
      case 26: {
        [self setGroupName:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasGroupId {
  return resultRefuseInviteJoinGroupNtfArgs.hasGroupId;
}
- (NSString*) groupId {
  return resultRefuseInviteJoinGroupNtfArgs.groupId;
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) setGroupId:(NSString*) value {
  resultRefuseInviteJoinGroupNtfArgs.hasGroupId = YES;
  resultRefuseInviteJoinGroupNtfArgs.groupId = value;
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) clearGroupId {
  resultRefuseInviteJoinGroupNtfArgs.hasGroupId = NO;
  resultRefuseInviteJoinGroupNtfArgs.groupId = @"";
  return self;
}
- (NSMutableArray *)refuseList {
  return resultRefuseInviteJoinGroupNtfArgs.refuseListArray;
}
- (RefuseInviteJoinGroupNtfArgs_NtfItem*)refuseListAtIndex:(NSUInteger)index {
  return [resultRefuseInviteJoinGroupNtfArgs refuseListAtIndex:index];
}
- (RefuseInviteJoinGroupNtfArgs_Builder *)addRefuseList:(RefuseInviteJoinGroupNtfArgs_NtfItem*)value {
  if (resultRefuseInviteJoinGroupNtfArgs.refuseListArray == nil) {
    resultRefuseInviteJoinGroupNtfArgs.refuseListArray = [[NSMutableArray alloc]init];
  }
  [resultRefuseInviteJoinGroupNtfArgs.refuseListArray addObject:value];
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_Builder *)setRefuseListArray:(NSArray *)array {
  resultRefuseInviteJoinGroupNtfArgs.refuseListArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_Builder *)clearRefuseList {
  resultRefuseInviteJoinGroupNtfArgs.refuseListArray = nil;
  return self;
}
- (BOOL) hasGroupName {
  return resultRefuseInviteJoinGroupNtfArgs.hasGroupName;
}
- (NSString*) groupName {
  return resultRefuseInviteJoinGroupNtfArgs.groupName;
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) setGroupName:(NSString*) value {
  resultRefuseInviteJoinGroupNtfArgs.hasGroupName = YES;
  resultRefuseInviteJoinGroupNtfArgs.groupName = value;
  return self;
}
- (RefuseInviteJoinGroupNtfArgs_Builder*) clearGroupName {
  resultRefuseInviteJoinGroupNtfArgs.hasGroupName = NO;
  resultRefuseInviteJoinGroupNtfArgs.groupName = @"";
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
