// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class SetGroupInfoArgs;
@class SetGroupInfoArgsBuilder;


typedef NS_ENUM(SInt32, UpdateGroupFieldFlags) {
  UpdateGroupFieldFlagsGroupName = 1,
  UpdateGroupFieldFlagsGroupConfig = 2,
  UpdateGroupFieldFlagsGroupPortraitUrl = 4,
};

BOOL UpdateGroupFieldFlagsIsValidValue(UpdateGroupFieldFlags value);
NSString *NSStringFromUpdateGroupFieldFlags(UpdateGroupFieldFlags value);


@interface SetGroupInfoArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SetGroupInfoArgs_groupId @"groupId"
#define SetGroupInfoArgs_groupName @"groupName"
#define SetGroupInfoArgs_groupConfig @"groupConfig"
#define SetGroupInfoArgs_updateFieldFlags @"updateFieldFlags"
#define SetGroupInfoArgs_groupPortraitUrl @"groupPortraitUrl"
@interface SetGroupInfoArgs : PBGeneratedMessage {
@private
  BOOL hasGroupConfig_:1;
  BOOL hasGroupId_:1;
  BOOL hasGroupName_:1;
  BOOL hasGroupPortraitUrl_:1;
  BOOL hasUpdateFieldFlags_:1;
  SInt32 groupConfig;
  NSString* groupId;
  NSString* groupName;
  NSString* groupPortraitUrl;
  UpdateGroupFieldFlags updateFieldFlags;
}
- (BOOL) hasGroupId;
- (BOOL) hasGroupName;
- (BOOL) hasGroupConfig;
- (BOOL) hasUpdateFieldFlags;
- (BOOL) hasGroupPortraitUrl;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) NSString* groupName;
@property (readonly) SInt32 groupConfig;
@property (readonly) UpdateGroupFieldFlags updateFieldFlags;
@property (readonly, strong) NSString* groupPortraitUrl;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetGroupInfoArgsBuilder*) builder;
+ (SetGroupInfoArgsBuilder*) builder;
+ (SetGroupInfoArgsBuilder*) builderWithPrototype:(SetGroupInfoArgs*) prototype;
- (SetGroupInfoArgsBuilder*) toBuilder;

+ (SetGroupInfoArgs*) parseFromData:(NSData*) data;
+ (SetGroupInfoArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupInfoArgs*) parseFromInputStream:(NSInputStream*) input;
+ (SetGroupInfoArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupInfoArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetGroupInfoArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetGroupInfoArgsBuilder : PBGeneratedMessage_Builder {
@private
  SetGroupInfoArgs* resultSetGroupInfoArgs;
}

- (SetGroupInfoArgs*) defaultInstance;

- (SetGroupInfoArgsBuilder*) clear;
- (SetGroupInfoArgsBuilder*) clone;

- (SetGroupInfoArgs*) build;
- (SetGroupInfoArgs*) buildPartial;

- (SetGroupInfoArgsBuilder*) mergeFrom:(SetGroupInfoArgs*) other;
- (SetGroupInfoArgsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetGroupInfoArgsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (SetGroupInfoArgsBuilder*) setGroupId:(NSString*) value;
- (SetGroupInfoArgsBuilder*) clearGroupId;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (SetGroupInfoArgsBuilder*) setGroupName:(NSString*) value;
- (SetGroupInfoArgsBuilder*) clearGroupName;

- (BOOL) hasGroupConfig;
- (SInt32) groupConfig;
- (SetGroupInfoArgsBuilder*) setGroupConfig:(SInt32) value;
- (SetGroupInfoArgsBuilder*) clearGroupConfig;

- (BOOL) hasUpdateFieldFlags;
- (UpdateGroupFieldFlags) updateFieldFlags;
- (SetGroupInfoArgsBuilder*) setUpdateFieldFlags:(UpdateGroupFieldFlags) value;
- (SetGroupInfoArgsBuilder*) clearUpdateFieldFlags;

- (BOOL) hasGroupPortraitUrl;
- (NSString*) groupPortraitUrl;
- (SetGroupInfoArgsBuilder*) setGroupPortraitUrl:(NSString*) value;
- (SetGroupInfoArgsBuilder*) clearGroupPortraitUrl;
@end


// @@protoc_insertion_point(global_scope)
