// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class SetGroupMemberInfoReqArgs;
@class SetGroupMemberInfoReqArgsBuilder;


typedef NS_ENUM(SInt32, UpdateGroupMemberFieldFlags) {
  UpdateGroupMemberFieldFlagsGroupMemberName = 1,
  UpdateGroupMemberFieldFlagsGroupMemberPortraitUrl = 2,
};

BOOL UpdateGroupMemberFieldFlagsIsValidValue(UpdateGroupMemberFieldFlags value);
NSString *NSStringFromUpdateGroupMemberFieldFlags(UpdateGroupMemberFieldFlags value);


@interface SetGroupMemberInfoReqArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define SetGroupMemberInfoReqArgs_groupId @"groupId"
#define SetGroupMemberInfoReqArgs_userId @"userId"
#define SetGroupMemberInfoReqArgs_newName @"newName"
#define SetGroupMemberInfoReqArgs_updateFieldFlags @"updateFieldFlags"
#define SetGroupMemberInfoReqArgs_groupMemberPortraitUrl @"groupMemberPortraitUrl"
@interface SetGroupMemberInfoReqArgs : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  BOOL hasUserId_:1;
  BOOL hasNewName_:1;
  BOOL hasGroupMemberPortraitUrl_:1;
  BOOL hasUpdateFieldFlags_:1;
  NSString* groupId;
  NSString* userId;
  NSString* newName;
  NSString* groupMemberPortraitUrl;
  UpdateGroupMemberFieldFlags updateFieldFlags;
}
- (BOOL) hasGroupId;
- (BOOL) hasUserId;
- (BOOL) hasNewName;
- (BOOL) hasUpdateFieldFlags;
- (BOOL) hasGroupMemberPortraitUrl;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) NSString* userId;
@property (readonly, strong) NS_RETURNS_NOT_RETAINED NSString* newName;
@property (readonly) UpdateGroupMemberFieldFlags updateFieldFlags;
@property (readonly, strong) NSString* groupMemberPortraitUrl;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SetGroupMemberInfoReqArgsBuilder*) builder;
+ (SetGroupMemberInfoReqArgsBuilder*) builder;
+ (SetGroupMemberInfoReqArgsBuilder*) builderWithPrototype:(SetGroupMemberInfoReqArgs*) prototype;
- (SetGroupMemberInfoReqArgsBuilder*) toBuilder;

+ (SetGroupMemberInfoReqArgs*) parseFromData:(NSData*) data;
+ (SetGroupMemberInfoReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupMemberInfoReqArgs*) parseFromInputStream:(NSInputStream*) input;
+ (SetGroupMemberInfoReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SetGroupMemberInfoReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SetGroupMemberInfoReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SetGroupMemberInfoReqArgsBuilder : PBGeneratedMessage_Builder {
@private
  SetGroupMemberInfoReqArgs* resultSetGroupMemberInfoReqArgs;
}

- (SetGroupMemberInfoReqArgs*) defaultInstance;

- (SetGroupMemberInfoReqArgsBuilder*) clear;
- (SetGroupMemberInfoReqArgsBuilder*) clone;

- (SetGroupMemberInfoReqArgs*) build;
- (SetGroupMemberInfoReqArgs*) buildPartial;

- (SetGroupMemberInfoReqArgsBuilder*) mergeFrom:(SetGroupMemberInfoReqArgs*) other;
- (SetGroupMemberInfoReqArgsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SetGroupMemberInfoReqArgsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (SetGroupMemberInfoReqArgsBuilder*) setGroupId:(NSString*) value;
- (SetGroupMemberInfoReqArgsBuilder*) clearGroupId;

- (BOOL) hasUserId;
- (NSString*) userId;
- (SetGroupMemberInfoReqArgsBuilder*) setUserId:(NSString*) value;
- (SetGroupMemberInfoReqArgsBuilder*) clearUserId;

- (BOOL) hasNewName;
- (NSString*) newName NS_RETURNS_NOT_RETAINED;
- (SetGroupMemberInfoReqArgsBuilder*) setNewName:(NSString*) value;
- (SetGroupMemberInfoReqArgsBuilder*) clearNewName;

- (BOOL) hasUpdateFieldFlags;
- (UpdateGroupMemberFieldFlags) updateFieldFlags;
- (SetGroupMemberInfoReqArgsBuilder*) setUpdateFieldFlags:(UpdateGroupMemberFieldFlags) value;
- (SetGroupMemberInfoReqArgsBuilder*) clearUpdateFieldFlags;

- (BOOL) hasGroupMemberPortraitUrl;
- (NSString*) groupMemberPortraitUrl;
- (SetGroupMemberInfoReqArgsBuilder*) setGroupMemberPortraitUrl:(NSString*) value;
- (SetGroupMemberInfoReqArgsBuilder*) clearGroupMemberPortraitUrl;
@end


// @@protoc_insertion_point(global_scope)
