// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class AddresslistIdDetailCombo;
@class AddresslistIdDetailCombo_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface AddresslistIdDetailComboRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface AddresslistIdDetailCombo : PBGeneratedMessage {
@private
  BOOL hasAddresslistId_:1;
  BOOL hasType_:1;
  BOOL hasAddresslistDetail_:1;
  NSString* addresslistId;
  NSString* type;
  NSData* addresslistDetail;
}
- (BOOL) hasAddresslistId;
- (BOOL) hasAddresslistDetail;
- (BOOL) hasType;
@property (readonly, retain) NSString* addresslistId;
@property (readonly, retain) NSData* addresslistDetail;
@property (readonly, retain) NSString* type;

+ (AddresslistIdDetailCombo*) defaultInstance;
- (AddresslistIdDetailCombo*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AddresslistIdDetailCombo_Builder*) builder;
+ (AddresslistIdDetailCombo_Builder*) builder;
+ (AddresslistIdDetailCombo_Builder*) builderWithPrototype:(AddresslistIdDetailCombo*) prototype;
- (AddresslistIdDetailCombo_Builder*) toBuilder;

+ (AddresslistIdDetailCombo*) parseFromData:(NSData*) data;
+ (AddresslistIdDetailCombo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddresslistIdDetailCombo*) parseFromInputStream:(NSInputStream*) input;
+ (AddresslistIdDetailCombo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (AddresslistIdDetailCombo*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (AddresslistIdDetailCombo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AddresslistIdDetailCombo_Builder : PBGeneratedMessage_Builder {
@private
  AddresslistIdDetailCombo* result;
}

- (AddresslistIdDetailCombo*) defaultInstance;

- (AddresslistIdDetailCombo_Builder*) clear;
- (AddresslistIdDetailCombo_Builder*) clone;

- (AddresslistIdDetailCombo*) build;
- (AddresslistIdDetailCombo*) buildPartial;

- (AddresslistIdDetailCombo_Builder*) mergeFrom:(AddresslistIdDetailCombo*) other;
- (AddresslistIdDetailCombo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AddresslistIdDetailCombo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasAddresslistId;
- (NSString*) addresslistId;
- (AddresslistIdDetailCombo_Builder*) setAddresslistId:(NSString*) value;
- (AddresslistIdDetailCombo_Builder*) clearAddresslistId;

- (BOOL) hasAddresslistDetail;
- (NSData*) addresslistDetail;
- (AddresslistIdDetailCombo_Builder*) setAddresslistDetail:(NSData*) value;
- (AddresslistIdDetailCombo_Builder*) clearAddresslistDetail;

- (BOOL) hasType;
- (NSString*) type;
- (AddresslistIdDetailCombo_Builder*) setType:(NSString*) value;
- (AddresslistIdDetailCombo_Builder*) clearType;
@end

