// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "AddresslistIdDetailCombo.pb.h"

@implementation AddresslistIdDetailComboRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [AddresslistIdDetailComboRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface AddresslistIdDetailCombo ()
@property (retain) NSString* addresslistId;
@property (retain) NSData* addresslistDetail;
@property (retain) NSString* type;
@end

@implementation AddresslistIdDetailCombo

- (BOOL) hasAddresslistId {
  return !!hasAddresslistId_;
}
- (void) setHasAddresslistId:(BOOL) value_ {
  hasAddresslistId_ = !!value_;
}
@synthesize addresslistId;
- (BOOL) hasAddresslistDetail {
  return !!hasAddresslistDetail_;
}
- (void) setHasAddresslistDetail:(BOOL) value_ {
  hasAddresslistDetail_ = !!value_;
}
@synthesize addresslistDetail;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value_ {
  hasType_ = !!value_;
}
@synthesize type;
- (void) dealloc {
  self.addresslistId = nil;
  self.addresslistDetail = nil;
  self.type = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.addresslistId = @"";
    self.addresslistDetail = [NSData data];
    self.type = @"";
  }
  return self;
}
static AddresslistIdDetailCombo* defaultAddresslistIdDetailComboInstance = nil;
+ (void) initialize {
  if (self == [AddresslistIdDetailCombo class]) {
    defaultAddresslistIdDetailComboInstance = [[AddresslistIdDetailCombo alloc] init];
  }
}
+ (AddresslistIdDetailCombo*) defaultInstance {
  return defaultAddresslistIdDetailComboInstance;
}
- (AddresslistIdDetailCombo*) defaultInstance {
  return defaultAddresslistIdDetailComboInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasAddresslistId) {
    [output writeString:1 value:self.addresslistId];
  }
  if (self.hasAddresslistDetail) {
    [output writeData:2 value:self.addresslistDetail];
  }
  if (self.hasType) {
    [output writeString:3 value:self.type];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasAddresslistId) {
    size_ += computeStringSize(1, self.addresslistId);
  }
  if (self.hasAddresslistDetail) {
    size_ += computeDataSize(2, self.addresslistDetail);
  }
  if (self.hasType) {
    size_ += computeStringSize(3, self.type);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (AddresslistIdDetailCombo*) parseFromData:(NSData*) data {
  return (AddresslistIdDetailCombo*)[[[AddresslistIdDetailCombo builder] mergeFromData:data] build];
}
+ (AddresslistIdDetailCombo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AddresslistIdDetailCombo*)[[[AddresslistIdDetailCombo builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (AddresslistIdDetailCombo*) parseFromInputStream:(NSInputStream*) input {
  return (AddresslistIdDetailCombo*)[[[AddresslistIdDetailCombo builder] mergeFromInputStream:input] build];
}
+ (AddresslistIdDetailCombo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AddresslistIdDetailCombo*)[[[AddresslistIdDetailCombo builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (AddresslistIdDetailCombo*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (AddresslistIdDetailCombo*)[[[AddresslistIdDetailCombo builder] mergeFromCodedInputStream:input] build];
}
+ (AddresslistIdDetailCombo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (AddresslistIdDetailCombo*)[[[AddresslistIdDetailCombo builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (AddresslistIdDetailCombo_Builder*) builder {
  return [[[AddresslistIdDetailCombo_Builder alloc] init] autorelease];
}
+ (AddresslistIdDetailCombo_Builder*) builderWithPrototype:(AddresslistIdDetailCombo*) prototype {
  return [[AddresslistIdDetailCombo builder] mergeFrom:prototype];
}
- (AddresslistIdDetailCombo_Builder*) builder {
  return [AddresslistIdDetailCombo builder];
}
- (AddresslistIdDetailCombo_Builder*) toBuilder {
  return [AddresslistIdDetailCombo builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasAddresslistId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"addresslistId", self.addresslistId];
  }
  if (self.hasAddresslistDetail) {
    [output appendFormat:@"%@%@: %@\n", indent, @"addresslistDetail", self.addresslistDetail];
  }
  if (self.hasType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"type", self.type];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[AddresslistIdDetailCombo class]]) {
    return NO;
  }
  AddresslistIdDetailCombo *otherMessage = other;
  return
      self.hasAddresslistId == otherMessage.hasAddresslistId &&
      (!self.hasAddresslistId || [self.addresslistId isEqual:otherMessage.addresslistId]) &&
      self.hasAddresslistDetail == otherMessage.hasAddresslistDetail &&
      (!self.hasAddresslistDetail || [self.addresslistDetail isEqual:otherMessage.addresslistDetail]) &&
      self.hasType == otherMessage.hasType &&
      (!self.hasType || [self.type isEqual:otherMessage.type]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasAddresslistId) {
    hashCode = hashCode * 31 + [self.addresslistId hash];
  }
  if (self.hasAddresslistDetail) {
    hashCode = hashCode * 31 + [self.addresslistDetail hash];
  }
  if (self.hasType) {
    hashCode = hashCode * 31 + [self.type hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface AddresslistIdDetailCombo_Builder()
@property (retain) AddresslistIdDetailCombo* result;
@end

@implementation AddresslistIdDetailCombo_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[AddresslistIdDetailCombo alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (AddresslistIdDetailCombo_Builder*) clear {
  self.result = [[[AddresslistIdDetailCombo alloc] init] autorelease];
  return self;
}
- (AddresslistIdDetailCombo_Builder*) clone {
  return [AddresslistIdDetailCombo builderWithPrototype:result];
}
- (AddresslistIdDetailCombo*) defaultInstance {
  return [AddresslistIdDetailCombo defaultInstance];
}
- (AddresslistIdDetailCombo*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (AddresslistIdDetailCombo*) buildPartial {
  AddresslistIdDetailCombo* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (AddresslistIdDetailCombo_Builder*) mergeFrom:(AddresslistIdDetailCombo*) other {
  if (other == [AddresslistIdDetailCombo defaultInstance]) {
    return self;
  }
  if (other.hasAddresslistId) {
    [self setAddresslistId:other.addresslistId];
  }
  if (other.hasAddresslistDetail) {
    [self setAddresslistDetail:other.addresslistDetail];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (AddresslistIdDetailCombo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (AddresslistIdDetailCombo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setAddresslistId:[input readString]];
        break;
      }
      case 18: {
        [self setAddresslistDetail:[input readData]];
        break;
      }
      case 26: {
        [self setType:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasAddresslistId {
  return result.hasAddresslistId;
}
- (NSString*) addresslistId {
  return result.addresslistId;
}
- (AddresslistIdDetailCombo_Builder*) setAddresslistId:(NSString*) value {
  result.hasAddresslistId = YES;
  result.addresslistId = value;
  return self;
}
- (AddresslistIdDetailCombo_Builder*) clearAddresslistId {
  result.hasAddresslistId = NO;
  result.addresslistId = @"";
  return self;
}
- (BOOL) hasAddresslistDetail {
  return result.hasAddresslistDetail;
}
- (NSData*) addresslistDetail {
  return result.addresslistDetail;
}
- (AddresslistIdDetailCombo_Builder*) setAddresslistDetail:(NSData*) value {
  result.hasAddresslistDetail = YES;
  result.addresslistDetail = value;
  return self;
}
- (AddresslistIdDetailCombo_Builder*) clearAddresslistDetail {
  result.hasAddresslistDetail = NO;
  result.addresslistDetail = [NSData data];
  return self;
}
- (BOOL) hasType {
  return result.hasType;
}
- (NSString*) type {
  return result.type;
}
- (AddresslistIdDetailCombo_Builder*) setType:(NSString*) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (AddresslistIdDetailCombo_Builder*) clearType {
  result.hasType = NO;
  result.type = @"";
  return self;
}
@end

