// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class DelAddressListReqArgs;
@class DelAddressListReqArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface DelAddressListReqArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface DelAddressListReqArgs : PBGeneratedMessage {
@private
  PBAppendableArray * addressIdsArray;
}
@property (readonly, retain) PBArray * addressIds;
- (NSString*)addressIdsAtIndex:(NSUInteger)index;

+ (DelAddressListReqArgs*) defaultInstance;
- (DelAddressListReqArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DelAddressListReqArgs_Builder*) builder;
+ (DelAddressListReqArgs_Builder*) builder;
+ (DelAddressListReqArgs_Builder*) builderWithPrototype:(DelAddressListReqArgs*) prototype;
- (DelAddressListReqArgs_Builder*) toBuilder;

+ (DelAddressListReqArgs*) parseFromData:(NSData*) data;
+ (DelAddressListReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DelAddressListReqArgs*) parseFromInputStream:(NSInputStream*) input;
+ (DelAddressListReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DelAddressListReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DelAddressListReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DelAddressListReqArgs_Builder : PBGeneratedMessage_Builder {
@private
  DelAddressListReqArgs* result;
}

- (DelAddressListReqArgs*) defaultInstance;

- (DelAddressListReqArgs_Builder*) clear;
- (DelAddressListReqArgs_Builder*) clone;

- (DelAddressListReqArgs*) build;
- (DelAddressListReqArgs*) buildPartial;

- (DelAddressListReqArgs_Builder*) mergeFrom:(DelAddressListReqArgs*) other;
- (DelAddressListReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DelAddressListReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (PBAppendableArray *)addressIds;
- (NSString*)addressIdsAtIndex:(NSUInteger)index;
- (DelAddressListReqArgs_Builder *)addAddressIds:(NSString*)value;
- (DelAddressListReqArgs_Builder *)setAddressIdsArray:(NSArray *)array;
- (DelAddressListReqArgs_Builder *)setAddressIdsValues:(const NSString* *)values count:(NSUInteger)count;
- (DelAddressListReqArgs_Builder *)clearAddressIds;
@end

