// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class GetAddressListReqArgs;
@class GetAddressListReqArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface GetAddressListReqArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GetAddressListReqArgs : PBGeneratedMessage {
@private
  BOOL hasIsDetail_:1;
  BOOL hasCountNum_:1;
  BOOL hasStartAddresslistId_:1;
  BOOL isDetail_:1;
  int32_t countNum;
  NSString* startAddresslistId;
  PBAppendableArray * addresslistIdsArray;
}
- (BOOL) hasIsDetail;
- (BOOL) hasStartAddresslistId;
- (BOOL) hasCountNum;
- (BOOL) isDetail;
@property (readonly, retain) PBArray * addresslistIds;
@property (readonly, retain) NSString* startAddresslistId;
@property (readonly) int32_t countNum;
- (NSString*)addresslistIdsAtIndex:(NSUInteger)index;

+ (GetAddressListReqArgs*) defaultInstance;
- (GetAddressListReqArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetAddressListReqArgs_Builder*) builder;
+ (GetAddressListReqArgs_Builder*) builder;
+ (GetAddressListReqArgs_Builder*) builderWithPrototype:(GetAddressListReqArgs*) prototype;
- (GetAddressListReqArgs_Builder*) toBuilder;

+ (GetAddressListReqArgs*) parseFromData:(NSData*) data;
+ (GetAddressListReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetAddressListReqArgs*) parseFromInputStream:(NSInputStream*) input;
+ (GetAddressListReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetAddressListReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetAddressListReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetAddressListReqArgs_Builder : PBGeneratedMessage_Builder {
@private
  GetAddressListReqArgs* result;
}

- (GetAddressListReqArgs*) defaultInstance;

- (GetAddressListReqArgs_Builder*) clear;
- (GetAddressListReqArgs_Builder*) clone;

- (GetAddressListReqArgs*) build;
- (GetAddressListReqArgs*) buildPartial;

- (GetAddressListReqArgs_Builder*) mergeFrom:(GetAddressListReqArgs*) other;
- (GetAddressListReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetAddressListReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasIsDetail;
- (BOOL) isDetail;
- (GetAddressListReqArgs_Builder*) setIsDetail:(BOOL) value;
- (GetAddressListReqArgs_Builder*) clearIsDetail;

- (PBAppendableArray *)addresslistIds;
- (NSString*)addresslistIdsAtIndex:(NSUInteger)index;
- (GetAddressListReqArgs_Builder *)addAddresslistIds:(NSString*)value;
- (GetAddressListReqArgs_Builder *)setAddresslistIdsArray:(NSArray *)array;
- (GetAddressListReqArgs_Builder *)setAddresslistIdsValues:(const NSString* *)values count:(NSUInteger)count;
- (GetAddressListReqArgs_Builder *)clearAddresslistIds;

- (BOOL) hasStartAddresslistId;
- (NSString*) startAddresslistId;
- (GetAddressListReqArgs_Builder*) setStartAddresslistId:(NSString*) value;
- (GetAddressListReqArgs_Builder*) clearStartAddresslistId;

- (BOOL) hasCountNum;
- (int32_t) countNum;
- (GetAddressListReqArgs_Builder*) setCountNum:(int32_t) value;
- (GetAddressListReqArgs_Builder*) clearCountNum;
@end

