// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class GetRelationShipReqArgs;
@class GetRelationShipReqArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface GetRelationShipReqArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface GetRelationShipReqArgs : PBGeneratedMessage {
@private
  BOOL hasExtentNo_:1;
  BOOL hasTargetUserId_:1;
  BOOL hasStartUserId_:1;
  int32_t extentNo;
  NSString* targetUserId;
  NSString* startUserId;
}
- (BOOL) hasExtentNo;
- (BOOL) hasTargetUserId;
- (BOOL) hasStartUserId;
@property (readonly) int32_t extentNo;
@property (readonly, retain) NSString* targetUserId;
@property (readonly, retain) NSString* startUserId;

+ (GetRelationShipReqArgs*) defaultInstance;
- (GetRelationShipReqArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GetRelationShipReqArgs_Builder*) builder;
+ (GetRelationShipReqArgs_Builder*) builder;
+ (GetRelationShipReqArgs_Builder*) builderWithPrototype:(GetRelationShipReqArgs*) prototype;
- (GetRelationShipReqArgs_Builder*) toBuilder;

+ (GetRelationShipReqArgs*) parseFromData:(NSData*) data;
+ (GetRelationShipReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRelationShipReqArgs*) parseFromInputStream:(NSInputStream*) input;
+ (GetRelationShipReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GetRelationShipReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GetRelationShipReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GetRelationShipReqArgs_Builder : PBGeneratedMessage_Builder {
@private
  GetRelationShipReqArgs* result;
}

- (GetRelationShipReqArgs*) defaultInstance;

- (GetRelationShipReqArgs_Builder*) clear;
- (GetRelationShipReqArgs_Builder*) clone;

- (GetRelationShipReqArgs*) build;
- (GetRelationShipReqArgs*) buildPartial;

- (GetRelationShipReqArgs_Builder*) mergeFrom:(GetRelationShipReqArgs*) other;
- (GetRelationShipReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GetRelationShipReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasExtentNo;
- (int32_t) extentNo;
- (GetRelationShipReqArgs_Builder*) setExtentNo:(int32_t) value;
- (GetRelationShipReqArgs_Builder*) clearExtentNo;

- (BOOL) hasTargetUserId;
- (NSString*) targetUserId;
- (GetRelationShipReqArgs_Builder*) setTargetUserId:(NSString*) value;
- (GetRelationShipReqArgs_Builder*) clearTargetUserId;

- (BOOL) hasStartUserId;
- (NSString*) startUserId;
- (GetRelationShipReqArgs_Builder*) setStartUserId:(NSString*) value;
- (GetRelationShipReqArgs_Builder*) clearStartUserId;
@end

