// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "UpAddressListReqArgs.pb.h"

@implementation UpAddressListReqArgsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UpAddressListReqArgsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface UpAddressListReqArgs ()
@property (retain) NSString* type;
@property (retain) PBAppendableArray * addressListArray;
@end

@implementation UpAddressListReqArgs

- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value_ {
  hasType_ = !!value_;
}
@synthesize type;
@synthesize addressListArray;
@dynamic addressList;
- (void) dealloc {
  self.type = nil;
  self.addressListArray = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.type = @"";
  }
  return self;
}
static UpAddressListReqArgs* defaultUpAddressListReqArgsInstance = nil;
+ (void) initialize {
  if (self == [UpAddressListReqArgs class]) {
    defaultUpAddressListReqArgsInstance = [[UpAddressListReqArgs alloc] init];
  }
}
+ (UpAddressListReqArgs*) defaultInstance {
  return defaultUpAddressListReqArgsInstance;
}
- (UpAddressListReqArgs*) defaultInstance {
  return defaultUpAddressListReqArgsInstance;
}
- (PBArray *)addressList {
  return addressListArray;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo*)addressListAtIndex:(NSUInteger)index {
  return [addressListArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasType) {
    [output writeString:1 value:self.type];
  }
  for (UpAddressListReqArgs_AddresslistIdDetailCombo *element in self.addressListArray) {
    [output writeMessage:2 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasType) {
    size_ += computeStringSize(1, self.type);
  }
  for (UpAddressListReqArgs_AddresslistIdDetailCombo *element in self.addressListArray) {
    size_ += computeMessageSize(2, element);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UpAddressListReqArgs*) parseFromData:(NSData*) data {
  return (UpAddressListReqArgs*)[[[UpAddressListReqArgs builder] mergeFromData:data] build];
}
+ (UpAddressListReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UpAddressListReqArgs*)[[[UpAddressListReqArgs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UpAddressListReqArgs*) parseFromInputStream:(NSInputStream*) input {
  return (UpAddressListReqArgs*)[[[UpAddressListReqArgs builder] mergeFromInputStream:input] build];
}
+ (UpAddressListReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UpAddressListReqArgs*)[[[UpAddressListReqArgs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UpAddressListReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (UpAddressListReqArgs*)[[[UpAddressListReqArgs builder] mergeFromCodedInputStream:input] build];
}
+ (UpAddressListReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UpAddressListReqArgs*)[[[UpAddressListReqArgs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UpAddressListReqArgs_Builder*) builder {
  return [[[UpAddressListReqArgs_Builder alloc] init] autorelease];
}
+ (UpAddressListReqArgs_Builder*) builderWithPrototype:(UpAddressListReqArgs*) prototype {
  return [[UpAddressListReqArgs builder] mergeFrom:prototype];
}
- (UpAddressListReqArgs_Builder*) builder {
  return [UpAddressListReqArgs builder];
}
- (UpAddressListReqArgs_Builder*) toBuilder {
  return [UpAddressListReqArgs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"type", self.type];
  }
  for (UpAddressListReqArgs_AddresslistIdDetailCombo* element in self.addressListArray) {
    [output appendFormat:@"%@%@ {\n", indent, @"addressList"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UpAddressListReqArgs class]]) {
    return NO;
  }
  UpAddressListReqArgs *otherMessage = other;
  return
      self.hasType == otherMessage.hasType &&
      (!self.hasType || [self.type isEqual:otherMessage.type]) &&
      [self.addressListArray isEqualToArray:otherMessage.addressListArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasType) {
    hashCode = hashCode * 31 + [self.type hash];
  }
  for (UpAddressListReqArgs_AddresslistIdDetailCombo* element in self.addressListArray) {
    hashCode = hashCode * 31 + [element hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UpAddressListReqArgs_AddresslistIdDetailCombo ()
@property (retain) NSString* addresslistId;
@property (retain) NSData* addresslistDetail;
@property (retain) NSString* type;
@end

@implementation UpAddressListReqArgs_AddresslistIdDetailCombo

- (BOOL) hasAddresslistId {
  return !!hasAddresslistId_;
}
- (void) setHasAddresslistId:(BOOL) value_ {
  hasAddresslistId_ = !!value_;
}
@synthesize addresslistId;
- (BOOL) hasAddresslistDetail {
  return !!hasAddresslistDetail_;
}
- (void) setHasAddresslistDetail:(BOOL) value_ {
  hasAddresslistDetail_ = !!value_;
}
@synthesize addresslistDetail;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) value_ {
  hasType_ = !!value_;
}
@synthesize type;
- (void) dealloc {
  self.addresslistId = nil;
  self.addresslistDetail = nil;
  self.type = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.addresslistId = @"";
    self.addresslistDetail = [NSData data];
    self.type = @"";
  }
  return self;
}
static UpAddressListReqArgs_AddresslistIdDetailCombo* defaultUpAddressListReqArgs_AddresslistIdDetailComboInstance = nil;
+ (void) initialize {
  if (self == [UpAddressListReqArgs_AddresslistIdDetailCombo class]) {
    defaultUpAddressListReqArgs_AddresslistIdDetailComboInstance = [[UpAddressListReqArgs_AddresslistIdDetailCombo alloc] init];
  }
}
+ (UpAddressListReqArgs_AddresslistIdDetailCombo*) defaultInstance {
  return defaultUpAddressListReqArgs_AddresslistIdDetailComboInstance;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo*) defaultInstance {
  return defaultUpAddressListReqArgs_AddresslistIdDetailComboInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasAddresslistId) {
    [output writeString:1 value:self.addresslistId];
  }
  if (self.hasAddresslistDetail) {
    [output writeData:2 value:self.addresslistDetail];
  }
  if (self.hasType) {
    [output writeString:3 value:self.type];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasAddresslistId) {
    size_ += computeStringSize(1, self.addresslistId);
  }
  if (self.hasAddresslistDetail) {
    size_ += computeDataSize(2, self.addresslistDetail);
  }
  if (self.hasType) {
    size_ += computeStringSize(3, self.type);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UpAddressListReqArgs_AddresslistIdDetailCombo*) parseFromData:(NSData*) data {
  return (UpAddressListReqArgs_AddresslistIdDetailCombo*)[[[UpAddressListReqArgs_AddresslistIdDetailCombo builder] mergeFromData:data] build];
}
+ (UpAddressListReqArgs_AddresslistIdDetailCombo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UpAddressListReqArgs_AddresslistIdDetailCombo*)[[[UpAddressListReqArgs_AddresslistIdDetailCombo builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UpAddressListReqArgs_AddresslistIdDetailCombo*) parseFromInputStream:(NSInputStream*) input {
  return (UpAddressListReqArgs_AddresslistIdDetailCombo*)[[[UpAddressListReqArgs_AddresslistIdDetailCombo builder] mergeFromInputStream:input] build];
}
+ (UpAddressListReqArgs_AddresslistIdDetailCombo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UpAddressListReqArgs_AddresslistIdDetailCombo*)[[[UpAddressListReqArgs_AddresslistIdDetailCombo builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UpAddressListReqArgs_AddresslistIdDetailCombo*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (UpAddressListReqArgs_AddresslistIdDetailCombo*)[[[UpAddressListReqArgs_AddresslistIdDetailCombo builder] mergeFromCodedInputStream:input] build];
}
+ (UpAddressListReqArgs_AddresslistIdDetailCombo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UpAddressListReqArgs_AddresslistIdDetailCombo*)[[[UpAddressListReqArgs_AddresslistIdDetailCombo builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) builder {
  return [[[UpAddressListReqArgs_AddresslistIdDetailCombo_Builder alloc] init] autorelease];
}
+ (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) builderWithPrototype:(UpAddressListReqArgs_AddresslistIdDetailCombo*) prototype {
  return [[UpAddressListReqArgs_AddresslistIdDetailCombo builder] mergeFrom:prototype];
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) builder {
  return [UpAddressListReqArgs_AddresslistIdDetailCombo builder];
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) toBuilder {
  return [UpAddressListReqArgs_AddresslistIdDetailCombo builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasAddresslistId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"addresslistId", self.addresslistId];
  }
  if (self.hasAddresslistDetail) {
    [output appendFormat:@"%@%@: %@\n", indent, @"addresslistDetail", self.addresslistDetail];
  }
  if (self.hasType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"type", self.type];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UpAddressListReqArgs_AddresslistIdDetailCombo class]]) {
    return NO;
  }
  UpAddressListReqArgs_AddresslistIdDetailCombo *otherMessage = other;
  return
      self.hasAddresslistId == otherMessage.hasAddresslistId &&
      (!self.hasAddresslistId || [self.addresslistId isEqual:otherMessage.addresslistId]) &&
      self.hasAddresslistDetail == otherMessage.hasAddresslistDetail &&
      (!self.hasAddresslistDetail || [self.addresslistDetail isEqual:otherMessage.addresslistDetail]) &&
      self.hasType == otherMessage.hasType &&
      (!self.hasType || [self.type isEqual:otherMessage.type]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasAddresslistId) {
    hashCode = hashCode * 31 + [self.addresslistId hash];
  }
  if (self.hasAddresslistDetail) {
    hashCode = hashCode * 31 + [self.addresslistDetail hash];
  }
  if (self.hasType) {
    hashCode = hashCode * 31 + [self.type hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UpAddressListReqArgs_AddresslistIdDetailCombo_Builder()
@property (retain) UpAddressListReqArgs_AddresslistIdDetailCombo* result;
@end

@implementation UpAddressListReqArgs_AddresslistIdDetailCombo_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[UpAddressListReqArgs_AddresslistIdDetailCombo alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) clear {
  self.result = [[[UpAddressListReqArgs_AddresslistIdDetailCombo alloc] init] autorelease];
  return self;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) clone {
  return [UpAddressListReqArgs_AddresslistIdDetailCombo builderWithPrototype:result];
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo*) defaultInstance {
  return [UpAddressListReqArgs_AddresslistIdDetailCombo defaultInstance];
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo*) buildPartial {
  UpAddressListReqArgs_AddresslistIdDetailCombo* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) mergeFrom:(UpAddressListReqArgs_AddresslistIdDetailCombo*) other {
  if (other == [UpAddressListReqArgs_AddresslistIdDetailCombo defaultInstance]) {
    return self;
  }
  if (other.hasAddresslistId) {
    [self setAddresslistId:other.addresslistId];
  }
  if (other.hasAddresslistDetail) {
    [self setAddresslistDetail:other.addresslistDetail];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setAddresslistId:[input readString]];
        break;
      }
      case 18: {
        [self setAddresslistDetail:[input readData]];
        break;
      }
      case 26: {
        [self setType:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasAddresslistId {
  return result.hasAddresslistId;
}
- (NSString*) addresslistId {
  return result.addresslistId;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) setAddresslistId:(NSString*) value {
  result.hasAddresslistId = YES;
  result.addresslistId = value;
  return self;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) clearAddresslistId {
  result.hasAddresslistId = NO;
  result.addresslistId = @"";
  return self;
}
- (BOOL) hasAddresslistDetail {
  return result.hasAddresslistDetail;
}
- (NSData*) addresslistDetail {
  return result.addresslistDetail;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) setAddresslistDetail:(NSData*) value {
  result.hasAddresslistDetail = YES;
  result.addresslistDetail = value;
  return self;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) clearAddresslistDetail {
  result.hasAddresslistDetail = NO;
  result.addresslistDetail = [NSData data];
  return self;
}
- (BOOL) hasType {
  return result.hasType;
}
- (NSString*) type {
  return result.type;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) setType:(NSString*) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo_Builder*) clearType {
  result.hasType = NO;
  result.type = @"";
  return self;
}
@end

@interface UpAddressListReqArgs_Builder()
@property (retain) UpAddressListReqArgs* result;
@end

@implementation UpAddressListReqArgs_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[UpAddressListReqArgs alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (UpAddressListReqArgs_Builder*) clear {
  self.result = [[[UpAddressListReqArgs alloc] init] autorelease];
  return self;
}
- (UpAddressListReqArgs_Builder*) clone {
  return [UpAddressListReqArgs builderWithPrototype:result];
}
- (UpAddressListReqArgs*) defaultInstance {
  return [UpAddressListReqArgs defaultInstance];
}
- (UpAddressListReqArgs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UpAddressListReqArgs*) buildPartial {
  UpAddressListReqArgs* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (UpAddressListReqArgs_Builder*) mergeFrom:(UpAddressListReqArgs*) other {
  if (other == [UpAddressListReqArgs defaultInstance]) {
    return self;
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.addressListArray.count > 0) {
    if (result.addressListArray == nil) {
      result.addressListArray = [[other.addressListArray copyWithZone:[other.addressListArray zone]] autorelease];
    } else {
      [result.addressListArray appendArray:other.addressListArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UpAddressListReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (UpAddressListReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setType:[input readString]];
        break;
      }
      case 18: {
        UpAddressListReqArgs_AddresslistIdDetailCombo_Builder* subBuilder = [UpAddressListReqArgs_AddresslistIdDetailCombo builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addAddressList:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasType {
  return result.hasType;
}
- (NSString*) type {
  return result.type;
}
- (UpAddressListReqArgs_Builder*) setType:(NSString*) value {
  result.hasType = YES;
  result.type = value;
  return self;
}
- (UpAddressListReqArgs_Builder*) clearType {
  result.hasType = NO;
  result.type = @"";
  return self;
}
- (PBAppendableArray *)addressList {
  return result.addressListArray;
}
- (UpAddressListReqArgs_AddresslistIdDetailCombo*)addressListAtIndex:(NSUInteger)index {
  return [result addressListAtIndex:index];
}
- (UpAddressListReqArgs_Builder *)addAddressList:(UpAddressListReqArgs_AddresslistIdDetailCombo*)value {
  if (result.addressListArray == nil) {
    result.addressListArray = [PBAppendableArray arrayWithValueType:PBArrayValueTypeObject];
  }
  [result.addressListArray addObject:value];
  return self;
}
- (UpAddressListReqArgs_Builder *)setAddressListArray:(NSArray *)array {
  result.addressListArray = [PBAppendableArray arrayWithArray:array valueType:PBArrayValueTypeObject];
  return self;
}
- (UpAddressListReqArgs_Builder *)setAddressListValues:(const UpAddressListReqArgs_AddresslistIdDetailCombo* *)values count:(NSUInteger)count {
  result.addressListArray = [PBAppendableArray arrayWithValues:values count:count valueType:PBArrayValueTypeObject];
  return self;
}
- (UpAddressListReqArgs_Builder *)clearAddressList {
  result.addressListArray = nil;
  return self;
}
@end

