// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class UploadBuddyListResult;
@class UploadBuddyListResult_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface UploadBuddyListResultRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface UploadBuddyListResult : PBGeneratedMessage {
@private
  BOOL hasStatusCode_:1;
  int32_t statusCode;
}
- (BOOL) hasStatusCode;
@property (readonly) int32_t statusCode;

+ (UploadBuddyListResult*) defaultInstance;
- (UploadBuddyListResult*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UploadBuddyListResult_Builder*) builder;
+ (UploadBuddyListResult_Builder*) builder;
+ (UploadBuddyListResult_Builder*) builderWithPrototype:(UploadBuddyListResult*) prototype;
- (UploadBuddyListResult_Builder*) toBuilder;

+ (UploadBuddyListResult*) parseFromData:(NSData*) data;
+ (UploadBuddyListResult*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadBuddyListResult*) parseFromInputStream:(NSInputStream*) input;
+ (UploadBuddyListResult*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadBuddyListResult*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UploadBuddyListResult*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UploadBuddyListResult_Builder : PBGeneratedMessage_Builder {
@private
  UploadBuddyListResult* result;
}

- (UploadBuddyListResult*) defaultInstance;

- (UploadBuddyListResult_Builder*) clear;
- (UploadBuddyListResult_Builder*) clone;

- (UploadBuddyListResult*) build;
- (UploadBuddyListResult*) buildPartial;

- (UploadBuddyListResult_Builder*) mergeFrom:(UploadBuddyListResult*) other;
- (UploadBuddyListResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UploadBuddyListResult_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatusCode;
- (int32_t) statusCode;
- (UploadBuddyListResult_Builder*) setStatusCode:(int32_t) value;
- (UploadBuddyListResult_Builder*) clearStatusCode;
@end

