// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class UploadBuddyListArgs;
@class UploadBuddyListArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface UploadBuddyListArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface UploadBuddyListArgs : PBGeneratedMessage {
@private
  BOOL hasOwnerId_:1;
  BOOL hasBuddyListVersion_:1;
  NSString* ownerId;
  NSString* buddyListVersion;
  PBAppendableArray * buddyListArray;
}
- (BOOL) hasOwnerId;
- (BOOL) hasBuddyListVersion;
@property (readonly, retain) NSString* ownerId;
@property (readonly, retain) NSString* buddyListVersion;
@property (readonly, retain) PBArray * buddyList;
- (NSString*)buddyListAtIndex:(NSUInteger)index;

+ (UploadBuddyListArgs*) defaultInstance;
- (UploadBuddyListArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UploadBuddyListArgs_Builder*) builder;
+ (UploadBuddyListArgs_Builder*) builder;
+ (UploadBuddyListArgs_Builder*) builderWithPrototype:(UploadBuddyListArgs*) prototype;
- (UploadBuddyListArgs_Builder*) toBuilder;

+ (UploadBuddyListArgs*) parseFromData:(NSData*) data;
+ (UploadBuddyListArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadBuddyListArgs*) parseFromInputStream:(NSInputStream*) input;
+ (UploadBuddyListArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UploadBuddyListArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UploadBuddyListArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UploadBuddyListArgs_Builder : PBGeneratedMessage_Builder {
@private
  UploadBuddyListArgs* result;
}

- (UploadBuddyListArgs*) defaultInstance;

- (UploadBuddyListArgs_Builder*) clear;
- (UploadBuddyListArgs_Builder*) clone;

- (UploadBuddyListArgs*) build;
- (UploadBuddyListArgs*) buildPartial;

- (UploadBuddyListArgs_Builder*) mergeFrom:(UploadBuddyListArgs*) other;
- (UploadBuddyListArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UploadBuddyListArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOwnerId;
- (NSString*) ownerId;
- (UploadBuddyListArgs_Builder*) setOwnerId:(NSString*) value;
- (UploadBuddyListArgs_Builder*) clearOwnerId;

- (BOOL) hasBuddyListVersion;
- (NSString*) buddyListVersion;
- (UploadBuddyListArgs_Builder*) setBuddyListVersion:(NSString*) value;
- (UploadBuddyListArgs_Builder*) clearBuddyListVersion;

- (PBAppendableArray *)buddyList;
- (NSString*)buddyListAtIndex:(NSUInteger)index;
- (UploadBuddyListArgs_Builder *)addBuddyList:(NSString*)value;
- (UploadBuddyListArgs_Builder *)setBuddyListArray:(NSArray *)array;
- (UploadBuddyListArgs_Builder *)setBuddyListValues:(const NSString* *)values count:(NSUInteger)count;
- (UploadBuddyListArgs_Builder *)clearBuddyList;
@end

