// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class RtcReplyRspArgs;
@class RtcReplyRspArgs_Builder;
#ifndef __has_feature
  #define __has_feature(x) 0 // Compatibility with non-clang compilers.
#endif // __has_feature

#ifndef NS_RETURNS_NOT_RETAINED
  #if __has_feature(attribute_ns_returns_not_retained)
    #define NS_RETURNS_NOT_RETAINED __attribute__((ns_returns_not_retained))
  #else
    #define NS_RETURNS_NOT_RETAINED
  #endif
#endif


@interface RtcReplyRspArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface RtcReplyRspArgs : PBGeneratedMessage {
@private
  BOOL hasRetCode_:1;
  int32_t retCode;
}
- (BOOL) hasRetCode;
@property (readonly) int32_t retCode;

+ (RtcReplyRspArgs*) defaultInstance;
- (RtcReplyRspArgs*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RtcReplyRspArgs_Builder*) builder;
+ (RtcReplyRspArgs_Builder*) builder;
+ (RtcReplyRspArgs_Builder*) builderWithPrototype:(RtcReplyRspArgs*) prototype;
- (RtcReplyRspArgs_Builder*) toBuilder;

+ (RtcReplyRspArgs*) parseFromData:(NSData*) data;
+ (RtcReplyRspArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RtcReplyRspArgs*) parseFromInputStream:(NSInputStream*) input;
+ (RtcReplyRspArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RtcReplyRspArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RtcReplyRspArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RtcReplyRspArgs_Builder : PBGeneratedMessage_Builder {
@private
  RtcReplyRspArgs* result;
}

- (RtcReplyRspArgs*) defaultInstance;

- (RtcReplyRspArgs_Builder*) clear;
- (RtcReplyRspArgs_Builder*) clone;

- (RtcReplyRspArgs*) build;
- (RtcReplyRspArgs*) buildPartial;

- (RtcReplyRspArgs_Builder*) mergeFrom:(RtcReplyRspArgs*) other;
- (RtcReplyRspArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RtcReplyRspArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRetCode;
- (int32_t) retCode;
- (RtcReplyRspArgs_Builder*) setRetCode:(int32_t) value;
- (RtcReplyRspArgs_Builder*) clearRetCode;
@end

