// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "RtcUpdateReqArgs.pb.h"

@implementation RtcUpdateReqArgsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [RtcUpdateReqArgsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface RtcUpdateReqArgs ()
@property (retain) RtcUpdateReqArgs_CallInfo* callInfo;
@property int32_t action;
@end

@implementation RtcUpdateReqArgs

- (BOOL) hasCallInfo {
  return !!hasCallInfo_;
}
- (void) setHasCallInfo:(BOOL) value_ {
  hasCallInfo_ = !!value_;
}
@synthesize callInfo;
- (BOOL) hasAction {
  return !!hasAction_;
}
- (void) setHasAction:(BOOL) value_ {
  hasAction_ = !!value_;
}
@synthesize action;
- (void) dealloc {
  self.callInfo = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.callInfo = [RtcUpdateReqArgs_CallInfo defaultInstance];
    self.action = 0;
  }
  return self;
}
static RtcUpdateReqArgs* defaultRtcUpdateReqArgsInstance = nil;
+ (void) initialize {
  if (self == [RtcUpdateReqArgs class]) {
    defaultRtcUpdateReqArgsInstance = [[RtcUpdateReqArgs alloc] init];
  }
}
+ (RtcUpdateReqArgs*) defaultInstance {
  return defaultRtcUpdateReqArgsInstance;
}
- (RtcUpdateReqArgs*) defaultInstance {
  return defaultRtcUpdateReqArgsInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasCallInfo) {
    [output writeMessage:1 value:self.callInfo];
  }
  if (self.hasAction) {
    [output writeInt32:2 value:self.action];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasCallInfo) {
    size_ += computeMessageSize(1, self.callInfo);
  }
  if (self.hasAction) {
    size_ += computeInt32Size(2, self.action);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (RtcUpdateReqArgs*) parseFromData:(NSData*) data {
  return (RtcUpdateReqArgs*)[[[RtcUpdateReqArgs builder] mergeFromData:data] build];
}
+ (RtcUpdateReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RtcUpdateReqArgs*)[[[RtcUpdateReqArgs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RtcUpdateReqArgs*) parseFromInputStream:(NSInputStream*) input {
  return (RtcUpdateReqArgs*)[[[RtcUpdateReqArgs builder] mergeFromInputStream:input] build];
}
+ (RtcUpdateReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RtcUpdateReqArgs*)[[[RtcUpdateReqArgs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RtcUpdateReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RtcUpdateReqArgs*)[[[RtcUpdateReqArgs builder] mergeFromCodedInputStream:input] build];
}
+ (RtcUpdateReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RtcUpdateReqArgs*)[[[RtcUpdateReqArgs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RtcUpdateReqArgs_Builder*) builder {
  return [[[RtcUpdateReqArgs_Builder alloc] init] autorelease];
}
+ (RtcUpdateReqArgs_Builder*) builderWithPrototype:(RtcUpdateReqArgs*) prototype {
  return [[RtcUpdateReqArgs builder] mergeFrom:prototype];
}
- (RtcUpdateReqArgs_Builder*) builder {
  return [RtcUpdateReqArgs builder];
}
- (RtcUpdateReqArgs_Builder*) toBuilder {
  return [RtcUpdateReqArgs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasCallInfo) {
    [output appendFormat:@"%@%@ {\n", indent, @"callInfo"];
    [self.callInfo writeDescriptionTo:output
                         withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }
  if (self.hasAction) {
    [output appendFormat:@"%@%@: %@\n", indent, @"action", [NSNumber numberWithInt:self.action]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[RtcUpdateReqArgs class]]) {
    return NO;
  }
  RtcUpdateReqArgs *otherMessage = other;
  return
      self.hasCallInfo == otherMessage.hasCallInfo &&
      (!self.hasCallInfo || [self.callInfo isEqual:otherMessage.callInfo]) &&
      self.hasAction == otherMessage.hasAction &&
      (!self.hasAction || self.action == otherMessage.action) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasCallInfo) {
    hashCode = hashCode * 31 + [self.callInfo hash];
  }
  if (self.hasAction) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.action] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface RtcUpdateReqArgs_CallInfo ()
@property (retain) NSString* peerUserId;
@property (retain) NSString* callId;
@end

@implementation RtcUpdateReqArgs_CallInfo

- (BOOL) hasPeerUserId {
  return !!hasPeerUserId_;
}
- (void) setHasPeerUserId:(BOOL) value_ {
  hasPeerUserId_ = !!value_;
}
@synthesize peerUserId;
- (BOOL) hasCallId {
  return !!hasCallId_;
}
- (void) setHasCallId:(BOOL) value_ {
  hasCallId_ = !!value_;
}
@synthesize callId;
- (void) dealloc {
  self.peerUserId = nil;
  self.callId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.peerUserId = @"";
    self.callId = @"";
  }
  return self;
}
static RtcUpdateReqArgs_CallInfo* defaultRtcUpdateReqArgs_CallInfoInstance = nil;
+ (void) initialize {
  if (self == [RtcUpdateReqArgs_CallInfo class]) {
    defaultRtcUpdateReqArgs_CallInfoInstance = [[RtcUpdateReqArgs_CallInfo alloc] init];
  }
}
+ (RtcUpdateReqArgs_CallInfo*) defaultInstance {
  return defaultRtcUpdateReqArgs_CallInfoInstance;
}
- (RtcUpdateReqArgs_CallInfo*) defaultInstance {
  return defaultRtcUpdateReqArgs_CallInfoInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasPeerUserId) {
    [output writeString:1 value:self.peerUserId];
  }
  if (self.hasCallId) {
    [output writeString:2 value:self.callId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasPeerUserId) {
    size_ += computeStringSize(1, self.peerUserId);
  }
  if (self.hasCallId) {
    size_ += computeStringSize(2, self.callId);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (RtcUpdateReqArgs_CallInfo*) parseFromData:(NSData*) data {
  return (RtcUpdateReqArgs_CallInfo*)[[[RtcUpdateReqArgs_CallInfo builder] mergeFromData:data] build];
}
+ (RtcUpdateReqArgs_CallInfo*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RtcUpdateReqArgs_CallInfo*)[[[RtcUpdateReqArgs_CallInfo builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (RtcUpdateReqArgs_CallInfo*) parseFromInputStream:(NSInputStream*) input {
  return (RtcUpdateReqArgs_CallInfo*)[[[RtcUpdateReqArgs_CallInfo builder] mergeFromInputStream:input] build];
}
+ (RtcUpdateReqArgs_CallInfo*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RtcUpdateReqArgs_CallInfo*)[[[RtcUpdateReqArgs_CallInfo builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RtcUpdateReqArgs_CallInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (RtcUpdateReqArgs_CallInfo*)[[[RtcUpdateReqArgs_CallInfo builder] mergeFromCodedInputStream:input] build];
}
+ (RtcUpdateReqArgs_CallInfo*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (RtcUpdateReqArgs_CallInfo*)[[[RtcUpdateReqArgs_CallInfo builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (RtcUpdateReqArgs_CallInfo_Builder*) builder {
  return [[[RtcUpdateReqArgs_CallInfo_Builder alloc] init] autorelease];
}
+ (RtcUpdateReqArgs_CallInfo_Builder*) builderWithPrototype:(RtcUpdateReqArgs_CallInfo*) prototype {
  return [[RtcUpdateReqArgs_CallInfo builder] mergeFrom:prototype];
}
- (RtcUpdateReqArgs_CallInfo_Builder*) builder {
  return [RtcUpdateReqArgs_CallInfo builder];
}
- (RtcUpdateReqArgs_CallInfo_Builder*) toBuilder {
  return [RtcUpdateReqArgs_CallInfo builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasPeerUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"peerUserId", self.peerUserId];
  }
  if (self.hasCallId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"callId", self.callId];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[RtcUpdateReqArgs_CallInfo class]]) {
    return NO;
  }
  RtcUpdateReqArgs_CallInfo *otherMessage = other;
  return
      self.hasPeerUserId == otherMessage.hasPeerUserId &&
      (!self.hasPeerUserId || [self.peerUserId isEqual:otherMessage.peerUserId]) &&
      self.hasCallId == otherMessage.hasCallId &&
      (!self.hasCallId || [self.callId isEqual:otherMessage.callId]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasPeerUserId) {
    hashCode = hashCode * 31 + [self.peerUserId hash];
  }
  if (self.hasCallId) {
    hashCode = hashCode * 31 + [self.callId hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface RtcUpdateReqArgs_CallInfo_Builder()
@property (retain) RtcUpdateReqArgs_CallInfo* result;
@end

@implementation RtcUpdateReqArgs_CallInfo_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RtcUpdateReqArgs_CallInfo alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RtcUpdateReqArgs_CallInfo_Builder*) clear {
  self.result = [[[RtcUpdateReqArgs_CallInfo alloc] init] autorelease];
  return self;
}
- (RtcUpdateReqArgs_CallInfo_Builder*) clone {
  return [RtcUpdateReqArgs_CallInfo builderWithPrototype:result];
}
- (RtcUpdateReqArgs_CallInfo*) defaultInstance {
  return [RtcUpdateReqArgs_CallInfo defaultInstance];
}
- (RtcUpdateReqArgs_CallInfo*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RtcUpdateReqArgs_CallInfo*) buildPartial {
  RtcUpdateReqArgs_CallInfo* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RtcUpdateReqArgs_CallInfo_Builder*) mergeFrom:(RtcUpdateReqArgs_CallInfo*) other {
  if (other == [RtcUpdateReqArgs_CallInfo defaultInstance]) {
    return self;
  }
  if (other.hasPeerUserId) {
    [self setPeerUserId:other.peerUserId];
  }
  if (other.hasCallId) {
    [self setCallId:other.callId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RtcUpdateReqArgs_CallInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RtcUpdateReqArgs_CallInfo_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setPeerUserId:[input readString]];
        break;
      }
      case 18: {
        [self setCallId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasPeerUserId {
  return result.hasPeerUserId;
}
- (NSString*) peerUserId {
  return result.peerUserId;
}
- (RtcUpdateReqArgs_CallInfo_Builder*) setPeerUserId:(NSString*) value {
  result.hasPeerUserId = YES;
  result.peerUserId = value;
  return self;
}
- (RtcUpdateReqArgs_CallInfo_Builder*) clearPeerUserId {
  result.hasPeerUserId = NO;
  result.peerUserId = @"";
  return self;
}
- (BOOL) hasCallId {
  return result.hasCallId;
}
- (NSString*) callId {
  return result.callId;
}
- (RtcUpdateReqArgs_CallInfo_Builder*) setCallId:(NSString*) value {
  result.hasCallId = YES;
  result.callId = value;
  return self;
}
- (RtcUpdateReqArgs_CallInfo_Builder*) clearCallId {
  result.hasCallId = NO;
  result.callId = @"";
  return self;
}
@end

@interface RtcUpdateReqArgs_Builder()
@property (retain) RtcUpdateReqArgs* result;
@end

@implementation RtcUpdateReqArgs_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[RtcUpdateReqArgs alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (RtcUpdateReqArgs_Builder*) clear {
  self.result = [[[RtcUpdateReqArgs alloc] init] autorelease];
  return self;
}
- (RtcUpdateReqArgs_Builder*) clone {
  return [RtcUpdateReqArgs builderWithPrototype:result];
}
- (RtcUpdateReqArgs*) defaultInstance {
  return [RtcUpdateReqArgs defaultInstance];
}
- (RtcUpdateReqArgs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (RtcUpdateReqArgs*) buildPartial {
  RtcUpdateReqArgs* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (RtcUpdateReqArgs_Builder*) mergeFrom:(RtcUpdateReqArgs*) other {
  if (other == [RtcUpdateReqArgs defaultInstance]) {
    return self;
  }
  if (other.hasCallInfo) {
    [self mergeCallInfo:other.callInfo];
  }
  if (other.hasAction) {
    [self setAction:other.action];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (RtcUpdateReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (RtcUpdateReqArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        RtcUpdateReqArgs_CallInfo_Builder* subBuilder = [RtcUpdateReqArgs_CallInfo builder];
        if (self.hasCallInfo) {
          [subBuilder mergeFrom:self.callInfo];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setCallInfo:[subBuilder buildPartial]];
        break;
      }
      case 16: {
        [self setAction:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasCallInfo {
  return result.hasCallInfo;
}
- (RtcUpdateReqArgs_CallInfo*) callInfo {
  return result.callInfo;
}
- (RtcUpdateReqArgs_Builder*) setCallInfo:(RtcUpdateReqArgs_CallInfo*) value {
  result.hasCallInfo = YES;
  result.callInfo = value;
  return self;
}
- (RtcUpdateReqArgs_Builder*) setCallInfoBuilder:(RtcUpdateReqArgs_CallInfo_Builder*) builderForValue {
  return [self setCallInfo:[builderForValue build]];
}
- (RtcUpdateReqArgs_Builder*) mergeCallInfo:(RtcUpdateReqArgs_CallInfo*) value {
  if (result.hasCallInfo &&
      result.callInfo != [RtcUpdateReqArgs_CallInfo defaultInstance]) {
    result.callInfo =
      [[[RtcUpdateReqArgs_CallInfo builderWithPrototype:result.callInfo] mergeFrom:value] buildPartial];
  } else {
    result.callInfo = value;
  }
  result.hasCallInfo = YES;
  return self;
}
- (RtcUpdateReqArgs_Builder*) clearCallInfo {
  result.hasCallInfo = NO;
  result.callInfo = [RtcUpdateReqArgs_CallInfo defaultInstance];
  return self;
}
- (BOOL) hasAction {
  return result.hasAction;
}
- (int32_t) action {
  return result.action;
}
- (RtcUpdateReqArgs_Builder*) setAction:(int32_t) value {
  result.hasAction = YES;
  result.action = value;
  return self;
}
- (RtcUpdateReqArgs_Builder*) clearAction {
  result.hasAction = NO;
  result.action = 0;
  return self;
}
@end

