// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "GetGroupFileCredencialResults.pb.h"

@implementation GetGroupFileCredencialResultsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [GetGroupFileCredencialResultsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface GetGroupFileCredencialResults ()
@property int32_t statusCode;
@property (retain) NSString* credential;
@end

@implementation GetGroupFileCredencialResults

- (BOOL) hasStatusCode {
  return !!hasStatusCode_;
}
- (void) setHasStatusCode:(BOOL) value_ {
  hasStatusCode_ = !!value_;
}
@synthesize statusCode;
- (BOOL) hasCredential {
  return !!hasCredential_;
}
- (void) setHasCredential:(BOOL) value_ {
  hasCredential_ = !!value_;
}
@synthesize credential;
- (void) dealloc {
  self.credential = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.statusCode = 0;
    self.credential = @"";
  }
  return self;
}
static GetGroupFileCredencialResults* defaultGetGroupFileCredencialResultsInstance = nil;
+ (void) initialize {
  if (self == [GetGroupFileCredencialResults class]) {
    defaultGetGroupFileCredencialResultsInstance = [[GetGroupFileCredencialResults alloc] init];
  }
}
+ (GetGroupFileCredencialResults*) defaultInstance {
  return defaultGetGroupFileCredencialResultsInstance;
}
- (GetGroupFileCredencialResults*) defaultInstance {
  return defaultGetGroupFileCredencialResultsInstance;
}
- (BOOL) isInitialized {
  if (!self.hasStatusCode) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasStatusCode) {
    [output writeInt32:1 value:self.statusCode];
  }
  if (self.hasCredential) {
    [output writeString:2 value:self.credential];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasStatusCode) {
    size_ += computeInt32Size(1, self.statusCode);
  }
  if (self.hasCredential) {
    size_ += computeStringSize(2, self.credential);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (GetGroupFileCredencialResults*) parseFromData:(NSData*) data {
  return (GetGroupFileCredencialResults*)[[[GetGroupFileCredencialResults builder] mergeFromData:data] build];
}
+ (GetGroupFileCredencialResults*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetGroupFileCredencialResults*)[[[GetGroupFileCredencialResults builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (GetGroupFileCredencialResults*) parseFromInputStream:(NSInputStream*) input {
  return (GetGroupFileCredencialResults*)[[[GetGroupFileCredencialResults builder] mergeFromInputStream:input] build];
}
+ (GetGroupFileCredencialResults*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetGroupFileCredencialResults*)[[[GetGroupFileCredencialResults builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetGroupFileCredencialResults*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (GetGroupFileCredencialResults*)[[[GetGroupFileCredencialResults builder] mergeFromCodedInputStream:input] build];
}
+ (GetGroupFileCredencialResults*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (GetGroupFileCredencialResults*)[[[GetGroupFileCredencialResults builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (GetGroupFileCredencialResults_Builder*) builder {
  return [[[GetGroupFileCredencialResults_Builder alloc] init] autorelease];
}
+ (GetGroupFileCredencialResults_Builder*) builderWithPrototype:(GetGroupFileCredencialResults*) prototype {
  return [[GetGroupFileCredencialResults builder] mergeFrom:prototype];
}
- (GetGroupFileCredencialResults_Builder*) builder {
  return [GetGroupFileCredencialResults builder];
}
- (GetGroupFileCredencialResults_Builder*) toBuilder {
  return [GetGroupFileCredencialResults builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasStatusCode) {
    [output appendFormat:@"%@%@: %@\n", indent, @"statusCode", [NSNumber numberWithInt:self.statusCode]];
  }
  if (self.hasCredential) {
    [output appendFormat:@"%@%@: %@\n", indent, @"credential", self.credential];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[GetGroupFileCredencialResults class]]) {
    return NO;
  }
  GetGroupFileCredencialResults *otherMessage = other;
  return
      self.hasStatusCode == otherMessage.hasStatusCode &&
      (!self.hasStatusCode || self.statusCode == otherMessage.statusCode) &&
      self.hasCredential == otherMessage.hasCredential &&
      (!self.hasCredential || [self.credential isEqual:otherMessage.credential]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  NSUInteger hashCode = 7;
  if (self.hasStatusCode) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInt:self.statusCode] hash];
  }
  if (self.hasCredential) {
    hashCode = hashCode * 31 + [self.credential hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface GetGroupFileCredencialResults_Builder()
@property (retain) GetGroupFileCredencialResults* result;
@end

@implementation GetGroupFileCredencialResults_Builder
@synthesize result;
- (void) dealloc {
  self.result = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.result = [[[GetGroupFileCredencialResults alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return result;
}
- (GetGroupFileCredencialResults_Builder*) clear {
  self.result = [[[GetGroupFileCredencialResults alloc] init] autorelease];
  return self;
}
- (GetGroupFileCredencialResults_Builder*) clone {
  return [GetGroupFileCredencialResults builderWithPrototype:result];
}
- (GetGroupFileCredencialResults*) defaultInstance {
  return [GetGroupFileCredencialResults defaultInstance];
}
- (GetGroupFileCredencialResults*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (GetGroupFileCredencialResults*) buildPartial {
  GetGroupFileCredencialResults* returnMe = [[result retain] autorelease];
  self.result = nil;
  return returnMe;
}
- (GetGroupFileCredencialResults_Builder*) mergeFrom:(GetGroupFileCredencialResults*) other {
  if (other == [GetGroupFileCredencialResults defaultInstance]) {
    return self;
  }
  if (other.hasStatusCode) {
    [self setStatusCode:other.statusCode];
  }
  if (other.hasCredential) {
    [self setCredential:other.credential];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (GetGroupFileCredencialResults_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (GetGroupFileCredencialResults_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setStatusCode:[input readInt32]];
        break;
      }
      case 18: {
        [self setCredential:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasStatusCode {
  return result.hasStatusCode;
}
- (int32_t) statusCode {
  return result.statusCode;
}
- (GetGroupFileCredencialResults_Builder*) setStatusCode:(int32_t) value {
  result.hasStatusCode = YES;
  result.statusCode = value;
  return self;
}
- (GetGroupFileCredencialResults_Builder*) clearStatusCode {
  result.hasStatusCode = NO;
  result.statusCode = 0;
  return self;
}
- (BOOL) hasCredential {
  return result.hasCredential;
}
- (NSString*) credential {
  return result.credential;
}
- (GetGroupFileCredencialResults_Builder*) setCredential:(NSString*) value {
  result.hasCredential = YES;
  result.credential = value;
  return self;
}
- (GetGroupFileCredencialResults_Builder*) clearCredential {
  result.hasCredential = NO;
  result.credential = @"";
  return self;
}
@end

