// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

// @@protoc_insertion_point(imports)

@class RefuseInviteJoinGroupNtfArgs;
@class RefuseInviteJoinGroupNtfArgs_Builder;
@class RefuseInviteJoinGroupNtfArgs_NtfItem;
@class RefuseInviteJoinGroupNtfArgs_NtfItem_Builder;



@interface RefuseInviteJoinGroupNtfArgsRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define RefuseInviteJoinGroupNtfArgs_groupId @"groupId"
#define RefuseInviteJoinGroupNtfArgs_refuseList @"refuseList"
#define RefuseInviteJoinGroupNtfArgs_groupName @"groupName"
@interface RefuseInviteJoinGroupNtfArgs : PBGeneratedMessage {
@private
  BOOL hasGroupId_:1;
  BOOL hasGroupName_:1;
  NSString* groupId;
  NSString* groupName;
  NSMutableArray * refuseListArray;
}
- (BOOL) hasGroupId;
- (BOOL) hasGroupName;
@property (readonly, strong) NSString* groupId;
@property (readonly, strong) NSArray * refuseList;
@property (readonly, strong) NSString* groupName;
- (RefuseInviteJoinGroupNtfArgs_NtfItem*)refuseListAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RefuseInviteJoinGroupNtfArgs_Builder*) builder;
+ (RefuseInviteJoinGroupNtfArgs_Builder*) builder;
+ (RefuseInviteJoinGroupNtfArgs_Builder*) builderWithPrototype:(RefuseInviteJoinGroupNtfArgs*) prototype;
- (RefuseInviteJoinGroupNtfArgs_Builder*) toBuilder;

+ (RefuseInviteJoinGroupNtfArgs*) parseFromData:(NSData*) data;
+ (RefuseInviteJoinGroupNtfArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefuseInviteJoinGroupNtfArgs*) parseFromInputStream:(NSInputStream*) input;
+ (RefuseInviteJoinGroupNtfArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefuseInviteJoinGroupNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RefuseInviteJoinGroupNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

#define NtfItem_invitedUserId @"invitedUserId"
#define NtfItem_invitedUserName @"invitedUserName"
@interface RefuseInviteJoinGroupNtfArgs_NtfItem : PBGeneratedMessage {
@private
  BOOL hasInvitedUserId_:1;
  BOOL hasInvitedUserName_:1;
  NSString* invitedUserId;
  NSString* invitedUserName;
}
- (BOOL) hasInvitedUserId;
- (BOOL) hasInvitedUserName;
@property (readonly, strong) NSString* invitedUserId;
@property (readonly, strong) NSString* invitedUserName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) builder;
+ (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) builder;
+ (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) builderWithPrototype:(RefuseInviteJoinGroupNtfArgs_NtfItem*) prototype;
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) toBuilder;

+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromData:(NSData*) data;
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromInputStream:(NSInputStream*) input;
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (RefuseInviteJoinGroupNtfArgs_NtfItem*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface RefuseInviteJoinGroupNtfArgs_NtfItem_Builder : PBGeneratedMessage_Builder {
@private
  RefuseInviteJoinGroupNtfArgs_NtfItem* resultNtfItem;
}

- (RefuseInviteJoinGroupNtfArgs_NtfItem*) defaultInstance;

- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) clear;
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) clone;

- (RefuseInviteJoinGroupNtfArgs_NtfItem*) build;
- (RefuseInviteJoinGroupNtfArgs_NtfItem*) buildPartial;

- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) mergeFrom:(RefuseInviteJoinGroupNtfArgs_NtfItem*) other;
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasInvitedUserId;
- (NSString*) invitedUserId;
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) setInvitedUserId:(NSString*) value;
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) clearInvitedUserId;

- (BOOL) hasInvitedUserName;
- (NSString*) invitedUserName;
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) setInvitedUserName:(NSString*) value;
- (RefuseInviteJoinGroupNtfArgs_NtfItem_Builder*) clearInvitedUserName;
@end

@interface RefuseInviteJoinGroupNtfArgs_Builder : PBGeneratedMessage_Builder {
@private
  RefuseInviteJoinGroupNtfArgs* resultRefuseInviteJoinGroupNtfArgs;
}

- (RefuseInviteJoinGroupNtfArgs*) defaultInstance;

- (RefuseInviteJoinGroupNtfArgs_Builder*) clear;
- (RefuseInviteJoinGroupNtfArgs_Builder*) clone;

- (RefuseInviteJoinGroupNtfArgs*) build;
- (RefuseInviteJoinGroupNtfArgs*) buildPartial;

- (RefuseInviteJoinGroupNtfArgs_Builder*) mergeFrom:(RefuseInviteJoinGroupNtfArgs*) other;
- (RefuseInviteJoinGroupNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (RefuseInviteJoinGroupNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasGroupId;
- (NSString*) groupId;
- (RefuseInviteJoinGroupNtfArgs_Builder*) setGroupId:(NSString*) value;
- (RefuseInviteJoinGroupNtfArgs_Builder*) clearGroupId;

- (NSMutableArray *)refuseList;
- (RefuseInviteJoinGroupNtfArgs_NtfItem*)refuseListAtIndex:(NSUInteger)index;
- (RefuseInviteJoinGroupNtfArgs_Builder *)addRefuseList:(RefuseInviteJoinGroupNtfArgs_NtfItem*)value;
- (RefuseInviteJoinGroupNtfArgs_Builder *)setRefuseListArray:(NSArray *)array;
- (RefuseInviteJoinGroupNtfArgs_Builder *)clearRefuseList;

- (BOOL) hasGroupName;
- (NSString*) groupName;
- (RefuseInviteJoinGroupNtfArgs_Builder*) setGroupName:(NSString*) value;
- (RefuseInviteJoinGroupNtfArgs_Builder*) clearGroupName;
@end


// @@protoc_insertion_point(global_scope)
