// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "SetGroupMemberInfoReqArgs.pb.h"
// @@protoc_insertion_point(imports)

@implementation SetGroupMemberInfoReqArgsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [SetGroupMemberInfoReqArgsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

BOOL UpdateGroupMemberFieldFlagsIsValidValue(UpdateGroupMemberFieldFlags value) {
  switch (value) {
    case UpdateGroupMemberFieldFlagsGroupMemberName:
    case UpdateGroupMemberFieldFlagsGroupMemberPortraitUrl:
      return YES;
    default:
      return NO;
  }
}
NSString *NSStringFromUpdateGroupMemberFieldFlags(UpdateGroupMemberFieldFlags value) {
  switch (value) {
    case UpdateGroupMemberFieldFlagsGroupMemberName:
      return @"UpdateGroupMemberFieldFlagsGroupMemberName";
    case UpdateGroupMemberFieldFlagsGroupMemberPortraitUrl:
      return @"UpdateGroupMemberFieldFlagsGroupMemberPortraitUrl";
    default:
      return nil;
  }
}

@interface SetGroupMemberInfoReqArgs ()
@property (strong) NSString* groupId;
@property (strong) NSString* userId;
@property (strong) NS_RETURNS_NOT_RETAINED NSString* newName;
@property UpdateGroupMemberFieldFlags updateFieldFlags;
@property (strong) NSString* groupMemberPortraitUrl;
@end

@implementation SetGroupMemberInfoReqArgs

- (BOOL) hasGroupId {
  return !!hasGroupId_;
}
- (void) setHasGroupId:(BOOL) _value_ {
  hasGroupId_ = !!_value_;
}
@synthesize groupId;
- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) _value_ {
  hasUserId_ = !!_value_;
}
@synthesize userId;
- (BOOL) hasNewName {
  return !!hasNewName_;
}
- (void) setHasNewName:(BOOL) _value_ {
  hasNewName_ = !!_value_;
}
@synthesize newName;
- (BOOL) hasUpdateFieldFlags {
  return !!hasUpdateFieldFlags_;
}
- (void) setHasUpdateFieldFlags:(BOOL) _value_ {
  hasUpdateFieldFlags_ = !!_value_;
}
@synthesize updateFieldFlags;
- (BOOL) hasGroupMemberPortraitUrl {
  return !!hasGroupMemberPortraitUrl_;
}
- (void) setHasGroupMemberPortraitUrl:(BOOL) _value_ {
  hasGroupMemberPortraitUrl_ = !!_value_;
}
@synthesize groupMemberPortraitUrl;
- (instancetype) init {
  if ((self = [super init])) {
    self.groupId = @"";
    self.userId = @"";
    self.newName = @"";
    self.updateFieldFlags = UpdateGroupMemberFieldFlagsGroupMemberName;
    self.groupMemberPortraitUrl = @"";
  }
  return self;
}
static SetGroupMemberInfoReqArgs* defaultSetGroupMemberInfoReqArgsInstance = nil;
+ (void) initialize {
  if (self == [SetGroupMemberInfoReqArgs class]) {
    defaultSetGroupMemberInfoReqArgsInstance = [[SetGroupMemberInfoReqArgs alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultSetGroupMemberInfoReqArgsInstance;
}
- (instancetype) defaultInstance {
  return defaultSetGroupMemberInfoReqArgsInstance;
}
- (BOOL) isInitialized {
  if (!self.hasGroupId) {
    return NO;
  }
  if (!self.hasUserId) {
    return NO;
  }
  if (!self.hasNewName) {
    return NO;
  }
  if (!self.hasUpdateFieldFlags) {
    return NO;
  }
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasGroupId) {
    [output writeString:1 value:self.groupId];
  }
  if (self.hasUserId) {
    [output writeString:2 value:self.userId];
  }
  if (self.hasNewName) {
    [output writeString:3 value:self.newName];
  }
  if (self.hasUpdateFieldFlags) {
    [output writeEnum:4 value:self.updateFieldFlags];
  }
  if (self.hasGroupMemberPortraitUrl) {
    [output writeString:5 value:self.groupMemberPortraitUrl];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasGroupId) {
    size_ += computeStringSize(1, self.groupId);
  }
  if (self.hasUserId) {
    size_ += computeStringSize(2, self.userId);
  }
  if (self.hasNewName) {
    size_ += computeStringSize(3, self.newName);
  }
  if (self.hasUpdateFieldFlags) {
    size_ += computeEnumSize(4, self.updateFieldFlags);
  }
  if (self.hasGroupMemberPortraitUrl) {
    size_ += computeStringSize(5, self.groupMemberPortraitUrl);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (SetGroupMemberInfoReqArgs*) parseFromData:(NSData*) data {
  return (SetGroupMemberInfoReqArgs*)[[[SetGroupMemberInfoReqArgs builder] mergeFromData:data] build];
}
+ (SetGroupMemberInfoReqArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SetGroupMemberInfoReqArgs*)[[[SetGroupMemberInfoReqArgs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (SetGroupMemberInfoReqArgs*) parseFromInputStream:(NSInputStream*) input {
  return (SetGroupMemberInfoReqArgs*)[[[SetGroupMemberInfoReqArgs builder] mergeFromInputStream:input] build];
}
+ (SetGroupMemberInfoReqArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SetGroupMemberInfoReqArgs*)[[[SetGroupMemberInfoReqArgs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SetGroupMemberInfoReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (SetGroupMemberInfoReqArgs*)[[[SetGroupMemberInfoReqArgs builder] mergeFromCodedInputStream:input] build];
}
+ (SetGroupMemberInfoReqArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (SetGroupMemberInfoReqArgs*)[[[SetGroupMemberInfoReqArgs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (SetGroupMemberInfoReqArgsBuilder*) builder {
  return [[SetGroupMemberInfoReqArgsBuilder alloc] init];
}
+ (SetGroupMemberInfoReqArgsBuilder*) builderWithPrototype:(SetGroupMemberInfoReqArgs*) prototype {
  return [[SetGroupMemberInfoReqArgs builder] mergeFrom:prototype];
}
- (SetGroupMemberInfoReqArgsBuilder*) builder {
  return [SetGroupMemberInfoReqArgs builder];
}
- (SetGroupMemberInfoReqArgsBuilder*) toBuilder {
  return [SetGroupMemberInfoReqArgs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasGroupId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"groupId", self.groupId];
  }
  if (self.hasUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userId", self.userId];
  }
  if (self.hasNewName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"newName", self.newName];
  }
  if (self.hasUpdateFieldFlags) {
    [output appendFormat:@"%@%@: %@\n", indent, @"updateFieldFlags", NSStringFromUpdateGroupMemberFieldFlags(self.updateFieldFlags)];
  }
  if (self.hasGroupMemberPortraitUrl) {
    [output appendFormat:@"%@%@: %@\n", indent, @"groupMemberPortraitUrl", self.groupMemberPortraitUrl];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[SetGroupMemberInfoReqArgs class]]) {
    return NO;
  }
  SetGroupMemberInfoReqArgs *otherMessage = other;
  return
      self.hasGroupId == otherMessage.hasGroupId &&
      (!self.hasGroupId || [self.groupId isEqual:otherMessage.groupId]) &&
      self.hasUserId == otherMessage.hasUserId &&
      (!self.hasUserId || [self.userId isEqual:otherMessage.userId]) &&
      self.hasNewName == otherMessage.hasNewName &&
      (!self.hasNewName || [self.newName isEqual:otherMessage.newName]) &&
      self.hasUpdateFieldFlags == otherMessage.hasUpdateFieldFlags &&
      (!self.hasUpdateFieldFlags || self.updateFieldFlags == otherMessage.updateFieldFlags) &&
      self.hasGroupMemberPortraitUrl == otherMessage.hasGroupMemberPortraitUrl &&
      (!self.hasGroupMemberPortraitUrl || [self.groupMemberPortraitUrl isEqual:otherMessage.groupMemberPortraitUrl]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasGroupId) {
    hashCode = hashCode * 31 + [self.groupId hash];
  }
  if (self.hasUserId) {
    hashCode = hashCode * 31 + [self.userId hash];
  }
  if (self.hasNewName) {
    hashCode = hashCode * 31 + [self.newName hash];
  }
  if (self.hasUpdateFieldFlags) {
    hashCode = hashCode * 31 + self.updateFieldFlags;
  }
  if (self.hasGroupMemberPortraitUrl) {
    hashCode = hashCode * 31 + [self.groupMemberPortraitUrl hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface SetGroupMemberInfoReqArgsBuilder()
@property (strong) SetGroupMemberInfoReqArgs* resultSetGroupMemberInfoReqArgs;
@end

@implementation SetGroupMemberInfoReqArgsBuilder
@synthesize resultSetGroupMemberInfoReqArgs;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultSetGroupMemberInfoReqArgs = [[SetGroupMemberInfoReqArgs alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultSetGroupMemberInfoReqArgs;
}
- (SetGroupMemberInfoReqArgsBuilder*) clear {
  self.resultSetGroupMemberInfoReqArgs = [[SetGroupMemberInfoReqArgs alloc] init];
  return self;
}
- (SetGroupMemberInfoReqArgsBuilder*) clone {
  return [SetGroupMemberInfoReqArgs builderWithPrototype:resultSetGroupMemberInfoReqArgs];
}
- (SetGroupMemberInfoReqArgs*) defaultInstance {
  return [SetGroupMemberInfoReqArgs defaultInstance];
}
- (SetGroupMemberInfoReqArgs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (SetGroupMemberInfoReqArgs*) buildPartial {
  SetGroupMemberInfoReqArgs* returnMe = resultSetGroupMemberInfoReqArgs;
  self.resultSetGroupMemberInfoReqArgs = nil;
  return returnMe;
}
- (SetGroupMemberInfoReqArgsBuilder*) mergeFrom:(SetGroupMemberInfoReqArgs*) other {
  if (other == [SetGroupMemberInfoReqArgs defaultInstance]) {
    return self;
  }
  if (other.hasGroupId) {
    [self setGroupId:other.groupId];
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasNewName) {
    [self setNewName:other.newName];
  }
  if (other.hasUpdateFieldFlags) {
    [self setUpdateFieldFlags:other.updateFieldFlags];
  }
  if (other.hasGroupMemberPortraitUrl) {
    [self setGroupMemberPortraitUrl:other.groupMemberPortraitUrl];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (SetGroupMemberInfoReqArgsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (SetGroupMemberInfoReqArgsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setGroupId:[input readString]];
        break;
      }
      case 18: {
        [self setUserId:[input readString]];
        break;
      }
      case 26: {
        [self setNewName:[input readString]];
        break;
      }
      case 32: {
        UpdateGroupMemberFieldFlags value = (UpdateGroupMemberFieldFlags)[input readEnum];
        if (UpdateGroupMemberFieldFlagsIsValidValue(value)) {
          [self setUpdateFieldFlags:value];
        } else {
          [unknownFields mergeVarintField:4 value:value];
        }
        break;
      }
      case 42: {
        [self setGroupMemberPortraitUrl:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasGroupId {
  return resultSetGroupMemberInfoReqArgs.hasGroupId;
}
- (NSString*) groupId {
  return resultSetGroupMemberInfoReqArgs.groupId;
}
- (SetGroupMemberInfoReqArgsBuilder*) setGroupId:(NSString*) value {
  resultSetGroupMemberInfoReqArgs.hasGroupId = YES;
  resultSetGroupMemberInfoReqArgs.groupId = value;
  return self;
}
- (SetGroupMemberInfoReqArgsBuilder*) clearGroupId {
  resultSetGroupMemberInfoReqArgs.hasGroupId = NO;
  resultSetGroupMemberInfoReqArgs.groupId = @"";
  return self;
}
- (BOOL) hasUserId {
  return resultSetGroupMemberInfoReqArgs.hasUserId;
}
- (NSString*) userId {
  return resultSetGroupMemberInfoReqArgs.userId;
}
- (SetGroupMemberInfoReqArgsBuilder*) setUserId:(NSString*) value {
  resultSetGroupMemberInfoReqArgs.hasUserId = YES;
  resultSetGroupMemberInfoReqArgs.userId = value;
  return self;
}
- (SetGroupMemberInfoReqArgsBuilder*) clearUserId {
  resultSetGroupMemberInfoReqArgs.hasUserId = NO;
  resultSetGroupMemberInfoReqArgs.userId = @"";
  return self;
}
- (BOOL) hasNewName {
  return resultSetGroupMemberInfoReqArgs.hasNewName;
}
- (NSString*) newName {
  return resultSetGroupMemberInfoReqArgs.newName;
}
- (SetGroupMemberInfoReqArgsBuilder*) setNewName:(NSString*) value {
  resultSetGroupMemberInfoReqArgs.hasNewName = YES;
  resultSetGroupMemberInfoReqArgs.newName = value;
  return self;
}
- (SetGroupMemberInfoReqArgsBuilder*) clearNewName {
  resultSetGroupMemberInfoReqArgs.hasNewName = NO;
  resultSetGroupMemberInfoReqArgs.newName = @"";
  return self;
}
- (BOOL) hasUpdateFieldFlags {
  return resultSetGroupMemberInfoReqArgs.hasUpdateFieldFlags;
}
- (UpdateGroupMemberFieldFlags) updateFieldFlags {
  return resultSetGroupMemberInfoReqArgs.updateFieldFlags;
}
- (SetGroupMemberInfoReqArgsBuilder*) setUpdateFieldFlags:(UpdateGroupMemberFieldFlags) value {
  resultSetGroupMemberInfoReqArgs.hasUpdateFieldFlags = YES;
  resultSetGroupMemberInfoReqArgs.updateFieldFlags = value;
  return self;
}
- (SetGroupMemberInfoReqArgsBuilder*) clearUpdateFieldFlags {
  resultSetGroupMemberInfoReqArgs.hasUpdateFieldFlags = NO;
  resultSetGroupMemberInfoReqArgs.updateFieldFlags = UpdateGroupMemberFieldFlagsGroupMemberName;
  return self;
}
- (BOOL) hasGroupMemberPortraitUrl {
  return resultSetGroupMemberInfoReqArgs.hasGroupMemberPortraitUrl;
}
- (NSString*) groupMemberPortraitUrl {
  return resultSetGroupMemberInfoReqArgs.groupMemberPortraitUrl;
}
- (SetGroupMemberInfoReqArgsBuilder*) setGroupMemberPortraitUrl:(NSString*) value {
  resultSetGroupMemberInfoReqArgs.hasGroupMemberPortraitUrl = YES;
  resultSetGroupMemberInfoReqArgs.groupMemberPortraitUrl = value;
  return self;
}
- (SetGroupMemberInfoReqArgsBuilder*) clearGroupMemberPortraitUrl {
  resultSetGroupMemberInfoReqArgs.hasGroupMemberPortraitUrl = NO;
  resultSetGroupMemberInfoReqArgs.groupMemberPortraitUrl = @"";
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
