// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "UserExitGroupNtfArgs.pb.h"
// @@protoc_insertion_point(imports)

@implementation UserExitGroupNtfArgsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UserExitGroupNtfArgsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface UserExitGroupNtfArgs ()
@property (strong) NSString* groupId;
@property SInt32 exitType;
@property (strong) NSString* exitUserId;
@property (strong) NSString* exitUserNickname;
@property (strong) NSString* sourceUserId;
@property (strong) NSString* sourceUserNickname;
@property (strong) NSString* groupName;
@end

@implementation UserExitGroupNtfArgs

- (BOOL) hasGroupId {
  return !!hasGroupId_;
}
- (void) setHasGroupId:(BOOL) _value_ {
  hasGroupId_ = !!_value_;
}
@synthesize groupId;
- (BOOL) hasExitType {
  return !!hasExitType_;
}
- (void) setHasExitType:(BOOL) _value_ {
  hasExitType_ = !!_value_;
}
@synthesize exitType;
- (BOOL) hasExitUserId {
  return !!hasExitUserId_;
}
- (void) setHasExitUserId:(BOOL) _value_ {
  hasExitUserId_ = !!_value_;
}
@synthesize exitUserId;
- (BOOL) hasExitUserNickname {
  return !!hasExitUserNickname_;
}
- (void) setHasExitUserNickname:(BOOL) _value_ {
  hasExitUserNickname_ = !!_value_;
}
@synthesize exitUserNickname;
- (BOOL) hasSourceUserId {
  return !!hasSourceUserId_;
}
- (void) setHasSourceUserId:(BOOL) _value_ {
  hasSourceUserId_ = !!_value_;
}
@synthesize sourceUserId;
- (BOOL) hasSourceUserNickname {
  return !!hasSourceUserNickname_;
}
- (void) setHasSourceUserNickname:(BOOL) _value_ {
  hasSourceUserNickname_ = !!_value_;
}
@synthesize sourceUserNickname;
- (BOOL) hasGroupName {
  return !!hasGroupName_;
}
- (void) setHasGroupName:(BOOL) _value_ {
  hasGroupName_ = !!_value_;
}
@synthesize groupName;
- (instancetype) init {
  if ((self = [super init])) {
    self.groupId = @"";
    self.exitType = 0;
    self.exitUserId = @"";
    self.exitUserNickname = @"";
    self.sourceUserId = @"";
    self.sourceUserNickname = @"";
    self.groupName = @"";
  }
  return self;
}
static UserExitGroupNtfArgs* defaultUserExitGroupNtfArgsInstance = nil;
+ (void) initialize {
  if (self == [UserExitGroupNtfArgs class]) {
    defaultUserExitGroupNtfArgsInstance = [[UserExitGroupNtfArgs alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultUserExitGroupNtfArgsInstance;
}
- (instancetype) defaultInstance {
  return defaultUserExitGroupNtfArgsInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasGroupId) {
    [output writeString:1 value:self.groupId];
  }
  if (self.hasExitType) {
    [output writeInt32:2 value:self.exitType];
  }
  if (self.hasExitUserId) {
    [output writeString:3 value:self.exitUserId];
  }
  if (self.hasExitUserNickname) {
    [output writeString:4 value:self.exitUserNickname];
  }
  if (self.hasSourceUserId) {
    [output writeString:5 value:self.sourceUserId];
  }
  if (self.hasSourceUserNickname) {
    [output writeString:6 value:self.sourceUserNickname];
  }
  if (self.hasGroupName) {
    [output writeString:7 value:self.groupName];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasGroupId) {
    size_ += computeStringSize(1, self.groupId);
  }
  if (self.hasExitType) {
    size_ += computeInt32Size(2, self.exitType);
  }
  if (self.hasExitUserId) {
    size_ += computeStringSize(3, self.exitUserId);
  }
  if (self.hasExitUserNickname) {
    size_ += computeStringSize(4, self.exitUserNickname);
  }
  if (self.hasSourceUserId) {
    size_ += computeStringSize(5, self.sourceUserId);
  }
  if (self.hasSourceUserNickname) {
    size_ += computeStringSize(6, self.sourceUserNickname);
  }
  if (self.hasGroupName) {
    size_ += computeStringSize(7, self.groupName);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (UserExitGroupNtfArgs*) parseFromData:(NSData*) data {
  return (UserExitGroupNtfArgs*)[[[UserExitGroupNtfArgs builder] mergeFromData:data] build];
}
+ (UserExitGroupNtfArgs*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserExitGroupNtfArgs*)[[[UserExitGroupNtfArgs builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (UserExitGroupNtfArgs*) parseFromInputStream:(NSInputStream*) input {
  return (UserExitGroupNtfArgs*)[[[UserExitGroupNtfArgs builder] mergeFromInputStream:input] build];
}
+ (UserExitGroupNtfArgs*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserExitGroupNtfArgs*)[[[UserExitGroupNtfArgs builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserExitGroupNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (UserExitGroupNtfArgs*)[[[UserExitGroupNtfArgs builder] mergeFromCodedInputStream:input] build];
}
+ (UserExitGroupNtfArgs*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (UserExitGroupNtfArgs*)[[[UserExitGroupNtfArgs builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (UserExitGroupNtfArgs_Builder*) builder {
  return [[UserExitGroupNtfArgs_Builder alloc] init];
}
+ (UserExitGroupNtfArgs_Builder*) builderWithPrototype:(UserExitGroupNtfArgs*) prototype {
  return [[UserExitGroupNtfArgs builder] mergeFrom:prototype];
}
- (UserExitGroupNtfArgs_Builder*) builder {
  return [UserExitGroupNtfArgs builder];
}
- (UserExitGroupNtfArgs_Builder*) toBuilder {
  return [UserExitGroupNtfArgs builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasGroupId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"groupId", self.groupId];
  }
  if (self.hasExitType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"exitType", [NSNumber numberWithInteger:self.exitType]];
  }
  if (self.hasExitUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"exitUserId", self.exitUserId];
  }
  if (self.hasExitUserNickname) {
    [output appendFormat:@"%@%@: %@\n", indent, @"exitUserNickname", self.exitUserNickname];
  }
  if (self.hasSourceUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"sourceUserId", self.sourceUserId];
  }
  if (self.hasSourceUserNickname) {
    [output appendFormat:@"%@%@: %@\n", indent, @"sourceUserNickname", self.sourceUserNickname];
  }
  if (self.hasGroupName) {
    [output appendFormat:@"%@%@: %@\n", indent, @"groupName", self.groupName];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[UserExitGroupNtfArgs class]]) {
    return NO;
  }
  UserExitGroupNtfArgs *otherMessage = other;
  return
      self.hasGroupId == otherMessage.hasGroupId &&
      (!self.hasGroupId || [self.groupId isEqual:otherMessage.groupId]) &&
      self.hasExitType == otherMessage.hasExitType &&
      (!self.hasExitType || self.exitType == otherMessage.exitType) &&
      self.hasExitUserId == otherMessage.hasExitUserId &&
      (!self.hasExitUserId || [self.exitUserId isEqual:otherMessage.exitUserId]) &&
      self.hasExitUserNickname == otherMessage.hasExitUserNickname &&
      (!self.hasExitUserNickname || [self.exitUserNickname isEqual:otherMessage.exitUserNickname]) &&
      self.hasSourceUserId == otherMessage.hasSourceUserId &&
      (!self.hasSourceUserId || [self.sourceUserId isEqual:otherMessage.sourceUserId]) &&
      self.hasSourceUserNickname == otherMessage.hasSourceUserNickname &&
      (!self.hasSourceUserNickname || [self.sourceUserNickname isEqual:otherMessage.sourceUserNickname]) &&
      self.hasGroupName == otherMessage.hasGroupName &&
      (!self.hasGroupName || [self.groupName isEqual:otherMessage.groupName]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasGroupId) {
    hashCode = hashCode * 31 + [self.groupId hash];
  }
  if (self.hasExitType) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.exitType] hash];
  }
  if (self.hasExitUserId) {
    hashCode = hashCode * 31 + [self.exitUserId hash];
  }
  if (self.hasExitUserNickname) {
    hashCode = hashCode * 31 + [self.exitUserNickname hash];
  }
  if (self.hasSourceUserId) {
    hashCode = hashCode * 31 + [self.sourceUserId hash];
  }
  if (self.hasSourceUserNickname) {
    hashCode = hashCode * 31 + [self.sourceUserNickname hash];
  }
  if (self.hasGroupName) {
    hashCode = hashCode * 31 + [self.groupName hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface UserExitGroupNtfArgs_Builder()
@property (strong) UserExitGroupNtfArgs* resultUserExitGroupNtfArgs;
@end

@implementation UserExitGroupNtfArgs_Builder
@synthesize resultUserExitGroupNtfArgs;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultUserExitGroupNtfArgs = [[UserExitGroupNtfArgs alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultUserExitGroupNtfArgs;
}
- (UserExitGroupNtfArgs_Builder*) clear {
  self.resultUserExitGroupNtfArgs = [[UserExitGroupNtfArgs alloc] init];
  return self;
}
- (UserExitGroupNtfArgs_Builder*) clone {
  return [UserExitGroupNtfArgs builderWithPrototype:resultUserExitGroupNtfArgs];
}
- (UserExitGroupNtfArgs*) defaultInstance {
  return [UserExitGroupNtfArgs defaultInstance];
}
- (UserExitGroupNtfArgs*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (UserExitGroupNtfArgs*) buildPartial {
  UserExitGroupNtfArgs* returnMe = resultUserExitGroupNtfArgs;
  self.resultUserExitGroupNtfArgs = nil;
  return returnMe;
}
- (UserExitGroupNtfArgs_Builder*) mergeFrom:(UserExitGroupNtfArgs*) other {
  if (other == [UserExitGroupNtfArgs defaultInstance]) {
    return self;
  }
  if (other.hasGroupId) {
    [self setGroupId:other.groupId];
  }
  if (other.hasExitType) {
    [self setExitType:other.exitType];
  }
  if (other.hasExitUserId) {
    [self setExitUserId:other.exitUserId];
  }
  if (other.hasExitUserNickname) {
    [self setExitUserNickname:other.exitUserNickname];
  }
  if (other.hasSourceUserId) {
    [self setSourceUserId:other.sourceUserId];
  }
  if (other.hasSourceUserNickname) {
    [self setSourceUserNickname:other.sourceUserNickname];
  }
  if (other.hasGroupName) {
    [self setGroupName:other.groupName];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (UserExitGroupNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (UserExitGroupNtfArgs_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setGroupId:[input readString]];
        break;
      }
      case 16: {
        [self setExitType:[input readInt32]];
        break;
      }
      case 26: {
        [self setExitUserId:[input readString]];
        break;
      }
      case 34: {
        [self setExitUserNickname:[input readString]];
        break;
      }
      case 42: {
        [self setSourceUserId:[input readString]];
        break;
      }
      case 50: {
        [self setSourceUserNickname:[input readString]];
        break;
      }
      case 58: {
        [self setGroupName:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasGroupId {
  return resultUserExitGroupNtfArgs.hasGroupId;
}
- (NSString*) groupId {
  return resultUserExitGroupNtfArgs.groupId;
}
- (UserExitGroupNtfArgs_Builder*) setGroupId:(NSString*) value {
  resultUserExitGroupNtfArgs.hasGroupId = YES;
  resultUserExitGroupNtfArgs.groupId = value;
  return self;
}
- (UserExitGroupNtfArgs_Builder*) clearGroupId {
  resultUserExitGroupNtfArgs.hasGroupId = NO;
  resultUserExitGroupNtfArgs.groupId = @"";
  return self;
}
- (BOOL) hasExitType {
  return resultUserExitGroupNtfArgs.hasExitType;
}
- (SInt32) exitType {
  return resultUserExitGroupNtfArgs.exitType;
}
- (UserExitGroupNtfArgs_Builder*) setExitType:(SInt32) value {
  resultUserExitGroupNtfArgs.hasExitType = YES;
  resultUserExitGroupNtfArgs.exitType = value;
  return self;
}
- (UserExitGroupNtfArgs_Builder*) clearExitType {
  resultUserExitGroupNtfArgs.hasExitType = NO;
  resultUserExitGroupNtfArgs.exitType = 0;
  return self;
}
- (BOOL) hasExitUserId {
  return resultUserExitGroupNtfArgs.hasExitUserId;
}
- (NSString*) exitUserId {
  return resultUserExitGroupNtfArgs.exitUserId;
}
- (UserExitGroupNtfArgs_Builder*) setExitUserId:(NSString*) value {
  resultUserExitGroupNtfArgs.hasExitUserId = YES;
  resultUserExitGroupNtfArgs.exitUserId = value;
  return self;
}
- (UserExitGroupNtfArgs_Builder*) clearExitUserId {
  resultUserExitGroupNtfArgs.hasExitUserId = NO;
  resultUserExitGroupNtfArgs.exitUserId = @"";
  return self;
}
- (BOOL) hasExitUserNickname {
  return resultUserExitGroupNtfArgs.hasExitUserNickname;
}
- (NSString*) exitUserNickname {
  return resultUserExitGroupNtfArgs.exitUserNickname;
}
- (UserExitGroupNtfArgs_Builder*) setExitUserNickname:(NSString*) value {
  resultUserExitGroupNtfArgs.hasExitUserNickname = YES;
  resultUserExitGroupNtfArgs.exitUserNickname = value;
  return self;
}
- (UserExitGroupNtfArgs_Builder*) clearExitUserNickname {
  resultUserExitGroupNtfArgs.hasExitUserNickname = NO;
  resultUserExitGroupNtfArgs.exitUserNickname = @"";
  return self;
}
- (BOOL) hasSourceUserId {
  return resultUserExitGroupNtfArgs.hasSourceUserId;
}
- (NSString*) sourceUserId {
  return resultUserExitGroupNtfArgs.sourceUserId;
}
- (UserExitGroupNtfArgs_Builder*) setSourceUserId:(NSString*) value {
  resultUserExitGroupNtfArgs.hasSourceUserId = YES;
  resultUserExitGroupNtfArgs.sourceUserId = value;
  return self;
}
- (UserExitGroupNtfArgs_Builder*) clearSourceUserId {
  resultUserExitGroupNtfArgs.hasSourceUserId = NO;
  resultUserExitGroupNtfArgs.sourceUserId = @"";
  return self;
}
- (BOOL) hasSourceUserNickname {
  return resultUserExitGroupNtfArgs.hasSourceUserNickname;
}
- (NSString*) sourceUserNickname {
  return resultUserExitGroupNtfArgs.sourceUserNickname;
}
- (UserExitGroupNtfArgs_Builder*) setSourceUserNickname:(NSString*) value {
  resultUserExitGroupNtfArgs.hasSourceUserNickname = YES;
  resultUserExitGroupNtfArgs.sourceUserNickname = value;
  return self;
}
- (UserExitGroupNtfArgs_Builder*) clearSourceUserNickname {
  resultUserExitGroupNtfArgs.hasSourceUserNickname = NO;
  resultUserExitGroupNtfArgs.sourceUserNickname = @"";
  return self;
}
- (BOOL) hasGroupName {
  return resultUserExitGroupNtfArgs.hasGroupName;
}
- (NSString*) groupName {
  return resultUserExitGroupNtfArgs.groupName;
}
- (UserExitGroupNtfArgs_Builder*) setGroupName:(NSString*) value {
  resultUserExitGroupNtfArgs.hasGroupName = YES;
  resultUserExitGroupNtfArgs.groupName = value;
  return self;
}
- (UserExitGroupNtfArgs_Builder*) clearGroupName {
  resultUserExitGroupNtfArgs.hasGroupName = NO;
  resultUserExitGroupNtfArgs.groupName = @"";
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
